= Overview

According to his Immanual Lutheran biography, xref:immanuel-lutheran:ROOT:DEC-BIO-Bleeke-01.adoc[Johann Heinrich Philipp Bleeke] was born 

[quote,Immanuel Lutheran biogrpahy for J.H.P. Bleeke]
____
zu Leeteln (Leteln), Kanton Windheim, Kreis Minden, Königr[eich] Preussen
____

in Leteln, in the canton of Windheim, the district of Minden, and the kingdom of Preußen (Prussia), and he emigrated
in 1834 to the U.S.; however, this was written many years after his birth in 1797, when the Canton system
introduced by Napolion did not exist. 

Below is a description of the individuals who emigrated and their relationships.

== Purpose

The purpose of this website is to:

* Document the precise family relationships of those Krückebergs who settled in Adams county, including any we were previously unaware of.
* Extend and document further their pedigree, their line of descent.
* Discover and document further other relatives or (to a lesser extent) close friends who also immigrated to Adams county in the chain of 
migration that brought the Bleeke, Weiland and Krückeberg and other German families to Adams county, Indiana.

== The Individuals and Their Relationships

Before listing the marriages betwen the families, these are the individuals who came.

=== Krückeberg Siblings and Cousin

==== Krückeberg siblings:

* Christine Luise Eleonore Krückeberg (About 1799 - ?)
* Johann Heinrich Krückeberg (12 Aug 1806 - ???)

==== Their Krückeberg cousins

* Carl Friedrich Gottlieb Krückeberg (21 May 1807 - 1850s [date of death unknown])

* Possibly two sisters of Carl Friedrich Gottlieb Krückeberg.

=== Bleeke Siblings

* Johann Heinrich Philip Bleeke (3 Nov 1797 to 18 Mar 1883)  
* Christian Friedrich Bleeke (28 Dec 1800 to 18 Nov 1889)

=== Weiland Father and Children

Fridrich Wilhelm Weÿland [also spelled: Weiland] and three of his married children:

* Luise Dorothea Weiland (2 Jan 1811 - 1870)
* Caroline Sophie Weiland (23 Jan 1808 - 1 Oct 1979)
* Heinrich Wilhelm Weÿland 

NOTE: These relationships need to be proven with documentation.

NOTE: Fridrich Wilhelm Weÿland's spouse Catharina Hahn did not emigrate as she likely was deceased.

=== Their Relationships Through Marriage

The marriage relationships are below:

todo: family groups sheet?

1. Christine Luise Eleonore Krückeberg (About 1799 - ?) married Christian Friedrich Bleeke (28 Dec 1800 - 18 Nov 1889).

2. Johann Heinrich Krückeberg (12 Aug 1806 to ??) married Caroline Sophie Weiland (23 Jan 1808 to 1 Oct 1879).

=== Religious Relationships


== Common Church Membership

The Weiland and Krückeberg families were members of the _St. Cosmos St. Damian_ Lutheran church in Petzen, Bückeburg, Schaumburg-Lippe.
