= TODO

== Confirm that Ilse Maria Möller is the correct wife of Johann Heinrich Blekcen

Her name was Anna Marie Elisabeth/Ilse Möller. The birth record in 1741 has
"Anna Catharina"?

== Jobst Heinrich Krückeberg and NLA 146

Rewrite the documents in gen/m/ancestry/p that concern the "two" Jobst
Heinrichs.

== WRITE

Work on the family ancestry proof. Gaps can be filled in later.
This will provide other research items for Dr. Möhle to research.

Add the jhk (1806) and CFK (1807) passenger lists.

== Add Further Research Strategy

* Add to the m/ancestry/nav.adoc, if not present, ~/gen/m/research/p/further-bueckeburg-documents.adoc
* And/or merge xref:ancestry:further-bueckeburg-documents.adoc[] with the
documents mentioned in xref:ancestry:who-is-the-father-of-jobst-heinrich.adoc[]

See: https://chatgpt.com/share/6979521a-a414-8004-b801-47a7da74ac19

NOTE: BE SURE to add xref evidentary links to xref:ancestry:who-is-the-father-of-jobst-heinrich.adoc[].

== Merge m/research/p files

Merge these two files into one:

* xref:research:next-bueckeburg-research-step.adoc[]
* xref:research:other-prosp-next-step-docs.adoc[]

== Rewrite m/research/bueckeburg-further-research.adoc

So it is to the point.

== Go Through theese Kirchenbücher

Looking for

=== The Second Jobst Heinrich Krückeberg from Evesen

I have looked for the second Jobst Heinrich Krückeberg, who states in his
petition of xref:nla:146:doc1.adoc[] that that he is an Einlieger who wants
to live "independently":

____
Up to now I have lived as a tenant with Wilharm No. 11
in Evesen, but I now wish to establish myself independently.
In front of Bärenbusch there lies a plot of land which
had previously already been inspected by the Forestry
Office, on the occasion that another person wished to
build there, but who was unable to pay for the plot.
____

The 2nd document in the module 146 case file, doc2.adoc, tells us:
* an Einlieger lodging at no. 11 Evesen
* a wanting become a holder of a new Stätte in Berenbusch
* his father is an Ackervogt in Arensburg
* who along with his wife is: gebürtig aus Evesen.

 in the Petzen
baptisms records of "Verzeichnis der Getauften und Konfirmierten 1641-1784".
I searched from ~1750 up to 1757, which is image #197


* I have gone through petzen-band1b Marriages up to image 57 up to image 57
* Look for baptism to Johann Tönnis Eggerding and Friedrich Kuhlmann
children. Looks in those years after their marriages. The purpose is to
learn when they still held no. 10 Berenbusch.
* go through the Deaths by Maiden Name

== Read

https://www.kirchner-raddestorf.de/heimat/regional/sozges.htm

== Merge information at nla/m/2728/p/index.adoc

See: https://chatgpt.com/share/697181a5-d3d0-8004-a311-5b8875bd7f98

Use the background information in the first half of
~/gen/m/research/next-bueckeburg-research-step.adoc
to replace the information at ~/gen/m/early-secular-records/index.adoc

Call it  "analysis of secular records between 1737
and 1747".

Use the 2nd half of

~/gen/m/research/next-bueckeburg-research-step.adoc

as the truly next step, but augment it with other documents like these
propsective Bückebuerg documents to research:

link:https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4894569[18 Landesvermessung
und Statistik] of the Alte Regierungsregistratur.

In addition there are 23 sections, one of these is "18 National Surveying and
Statistics".

== Jobst Heinrich Weÿland is Mentioned in Dr. Möhle's Research 

The first five images of Berenbusch (of the many images from Dr. Moehle),
which are  from the *Survey of the Villages of Evesen, Berenbusch, and Nordholz*
(Vermessung der Dörfer Evesen, Berenbusch und Nordholz) from 1745.

See 
file:///home/kurt/backup_folder/bueckeburg_moehle_research/GrosFichiers-Sylvia-Möhle/Krueckeberg/NLA%20BU%20L%202%20L%20Nr.%202713[NLA
BU L 2 L Nr. 27/13].

== Add to Johann Heinrich (1705-175) Event Table

Add these facts:

* by 1747 he is the Brinksitzer of no. 10 Berenbusch
* that the former holder of no. 10 Berenbusch was also a baptismal sponsor
  in 1728 of Johann Heinrich's son, Johann Friedrich.

== Email Meike Strattmann this Question

Sehr geehrte Damen und Herren,

Ich arbeite mit mehreren Akten des Amtes Bückeburg aus dem späten 18.
Jahrhundert (u. a. Rentkammer- und Ausweisungsakten zu Berenbusch, Evesen
und Umgebung).

In diesen Unterlagen werden die Bezeichnungen **Kolon**, **Brinksitzer**
und **Kötter** teilweise für dieselbe Person verwendet.  Ich möchte daher
gern wissen, wie diese Begriffe im **Amt Bückeburg** administrativ
verstanden wurden:

* Gab es lokale Ordnungen oder Vorschriften, die diese Kategorien
  definierten?
* Unterschieden sie sich rechtlich (z. B. in Bezug auf Besitz, Abgaben oder
  Rechte)?
* Oder wurden sie eher beschreibend als formal-juristisch verwendet?

Falls es dazu einschlägige Ordnungen, Register oder Sekundärliteratur gibt,
wäre ich für entsprechende Hinweise sehr dankbar.

Mit freundlichen Grüßen Kurt Krueckeberg

== Enhance the post-1827 Kirchenbuch Mirofiche Images

These are in
~/backup_folder/NLA_Auftrag_Krückeberg_2024-06-16_NLA_689_1237_98_354/Recherche_Krückeberg.

* Enhance them
* Do Transkribus text recognition
* Add them to ~/gen.

== Add to Möhle Bückebuerg Individual's to Research

* https://docs.krueckeberg.org/genealogy/1.0/research/RR-Krueckeberg-1700-1760-TargetRecords.html
* https://docs.krueckeberg.org/genealogy/1.0/research/jobst-hk-1765-1822-guild-records.html
* Schäkel death record.
* Carl Freid. Bleeke's military record

== Review Dr. Moehle's Transliterations

* Confirm that "10.)" in the image
`m/research/images/NLA_BU_L_101a_A_Nr.140.enlarged.png` is "No. 10 Berenbsuch"?

* Ask Dr. Möhle why she mentioned marrying into ownership of no. 10
Berenbusch.

=== Review the Purpose of the Research with the Outcome

Review the purpose at
xref:research:RR-Krueckeberg-MasterResearch-1700-1850.adoc[] with what was
found xref:research:moehle:moehle_transliterations_buekckeburg.adoc[].

She apparently only did the first part of the research: examine documents
from 1700-1760. She didn't do the 2^nd^ phase or the do the
Krueckeberg/Bleeke or Guild research.

I do have microfiche images that I requested over the summer that I might
be able to enhance.

=== Create a New Page or Section

Move the section on the purpose 
xref:research:RR-Krueckeberg-MasterResearch-1700-1850.adoc[] and the
anylysis of what was found
xref:research:moehle:moehle_transliterations_buekckeburg.adoc[]
into a separate AsciiDoc section, top-level section, of the `genealogy`
compoenent.

== Rework and Convert Dr. Moehle Work to AsciiDoc

Convert `modules/background/attachments/Moehle_Report_on_History_of_Schaumburg-Lippe.pdf`
to `.adoc` files.

== Review What is Obvious

Take the todo-items below. What items are obvious annd can be built upon?

== Where did the Krückeberg's Live

Q: Which villages are mentioned in the Petzen parish church register records
for Krückebergs who were eiterh born, baptized, confirmed, married or
buried list their village as Berenbusch?

A: Just two villages are mentioned Berenbusch and Evesen. From 1725 to ??
only Berenbusch is mentioned. Evesen is mentioned.

=== Plan to Anaylze "Krückeberg aus Berenbusch"

The use of only the surname and the omission of the given names of the
father in the early birth records may mean there was only one Krückeberg
couple-family name Krückeberg in Berenbusch, so it was not necessary to
mention the father's full name. 

*Plan:* Compare adjacent records to those using "Krueckeberg aus/in
Berenbusch" for similiar surname-only usage and assess how many records
use the father's fullname versus those than only use the surname.
 
== Where Did Carl Friedrich Gottlieb's Sibling Live?

The confirmation records for his two sisters mention only Berenbusch.

If one looks for the marriage record of Johann Friedrich Gottlieb's
sisters, and if they married in Petzen, they will have their address, and
we can learn if they lived at no. 10 Berenbusch.
 
== Look Record for Death of Ilse Anna Marie Elisabeth née Schakel using her maiden name

I could not find a death record for Ilse Anna Marie Elisabeth under the
surname Krückeberg.

She married Johann Heinrich Krückeberg on 7 Nov. 1773. She must be the
"alte Krüeckeberg als Großmutter" in the 1792 baptism record of Jobst
Heinrich Krückeberg's daughter. She would be Jobst step-mother since he
was eight years old. 

So her death would have occurred between the 1792 baptisam an 1802 when
Johann Heinrich married for the third time.

*Note:* Perhaps her burial record is under her *maiden name* written in this manner:

Ilse Anna Marie Elisabeth Schakel .... des Johann Heinrich Krückebergs Ehehfrau.

== Add NLA Facts to the Event Tables

Use the new event table design shown in `m/ancestry/p/new-event-table-design.adoc`.

Read through and add to the respective event tables the information in the NLA documents

Add Information such as:

In "The plots allocated to the colonist Krückeberg No. 10 in Berenbusch for
the enlargement of his farmyard and garden", we learn:

. Jobst Heinrich is namned the Colon of no. 10 Berenbusch.
. We have a map either of the enlarged yard and garden area, the extra yard
  and garden area, or a map the total area after the enlargement
. A description of it being near the road.
. That Kötter Weiland lives nearby.

In "Die Stätte Nr. 18 zu Berenbusch", we learn:

. We learn that Jobst Heinrich is a tailor who is "ein Einlieger bei
  Wilharms no. 11 Evesen".
. The Bückeburg Amt reports his father was an Ackervogt in Arenbsburg.
. We learn--I think--where no. 18 Berenbusch was located.
. we know that Johann Heinrich (1806-1879) owned it (no. 10 Berenbusch),
because the "Colon Krückeberg" who sold it in the fall of 1849 said he
was doing so because he planned to immigrate to the U.S. that same
month--September?--to the U.S.
. In later documents in its case file, we learn Carl Friedrich (born 1807)
petitions to sell no. 18 Berenbusch in the fall of 1850 because he has
relatives in America who are doing well, and he wants to join them in
America.
. Carl Friedrich also mentions he has relatives in America, who are doing
  well.

In the case file "Ein dem Colon Krückeberg Nr. 10 in Berenbusch aus
Kammerkasse dargeliehenes Kapital von 200 Reichstaler Crt.", we learn:

. The debt Johann Heinrich inherits.
. His father's poor health...
. How debt passes onto one's heirs.
. Details of the Söhren Weide
. That the Prince of Schaumburg-Lippe will make the final decision.

In the case file concerning the "Die Stätte Nr. 10 zu Berenbusch", we
learn:

. That medical expenses impoverished Jobst Heinrich's widow
. That certain feudal manual labor obligations still exist, from which she
  is requesting relief.
. From its later 1849 documents, we learn that Johann Heinrich requests to
  have his sale approved because he will immigrate to America in Sept? of
1849.

From the case file, 
. Its financial impact.
. Jobst Heinrich's father was an Ackervogt

== Records to help identify Johann Heinrich (1744-1822)

From https://chatgpt.com/share/695aff31-7adc-8004-b9f0-cd0a5bb5c4fa

____
Please check the Amtsprotokolle (Amt Bückeburg) and
Kammerrechnungen/Heberegister for Berenbusch to see whether Johann Heinrich
Krückeberg is named as holder or payer of a Stätte (later Nr. 10), or is
identified as father of Jobst Heinrich Krückeberg. I only need the earliest
occurrence or confirmation that none exists.
____

== Jobst Heinrich Krückeberg born 1733

Are there no other records of him?

== Work on the .adoc files in m/background/underdevelopment

See `~/gen/m/background/underdevelopment/todo.adoc` and `~/gen/m/background/todo.adoc`.

== Watch

https://www.youtube.com/watch?v=rHfbVYAru7s
== Schamerloh Records in Buchholz

Find them.

== Were Wilharms Baptismal Sponsors?

Note Wilharm it's not only where Jobst Heinrich lodged in Evesen, but Wilharms were also
sponsors in his family tree--right?

== TODO Next
 
Convert Dr. Möhle work to .adoc pages.

Finish what I began in m/background/stand-meaning.adoc and the other .adoc files
in m/background/p/underdevelopment.

== Add NLA 146 and 120 Material to Ancestry Event Tables

== Examine Berenbusch numbers

Use this:

> rg 'B.[hr][er]nbusch' *.adoc | sort -t: -k1.7,1.11 -k1.12,1.12|less

== Baptism Birthplace Records Wrong?

Are some baptism's birthplaces wrong?

In baptism entries for two of the children of Carl Friedrich Gottlieb
Krückeberg we have two different birthplaces given--or are these no
birthplaces but current residences?  The birthplace for Carl Friedrich
born in 1807 and the daughter born the next year is given only as
"Berenbusch". In these records, there is a column for the "Name, Stand,
Religion and Birthplace of the Father". However, for the 1807 birth of
Carl Friedrich, this column contains "Carl Friedrich Gottlieb Krückeberg.
Schneider u. Einlieger in n. 14 in Bärenbusch. Luth. Conf.", while for the
the 1812 birth of daughter Carloline Dorothee Krückeberg it has "Carl
Friedrich Gottlieb Krückeberg n. 18 in Bärenbusch Luth. Conf.".

So is "n. 14 Berenbsuch" and "n. 18 Berenbusch" the address at the time
the child was born despite the column stating it is the "birthplace of the
father"? The actual birth record of Carl Friedrich Gottlieb is of no help
in answering this question since it only mentions Berenbusch.  

Answer: The answer is given in the column "Wohnort der Eltern", which
has the same address as that of the father.

== What 146 Tells Us

I tells us that Jobst Heinrich's father was an Ackervogt in Arensburg, which was the 
area in Steinbergen as ChatGPT explained:

____
1. Arensburg was not originally a town name but referred to a local castle and administrative area
In the territory of the historical County/Principality of Schaumburg-Lippe, Arensburg referred primarily to a
castle (Schloss/Arensburg) and the surrounding Amt (administrative district) near the village of Steinbergen in
what is now the district of Schaumburg in Lower Saxony, Germany. This “Amt Arensburg” formed part of the
territorial structure of Schaumburg-Lippe along with other Ämter such as Bückeburg, Hagenburg, and Stadthagen
____

Would there be records for a Ackervogt in Steinbergen?

=== Read the Zotero Links in Schaumburg-Lippe

== Rewrite Dr. Moehle's Work

Should this material be merge with Dr. Moehle's work.

== Research to Do

=== Map

Look for NLA case file for a Berenbusch site that belongs to a non-Krueckeberg that contains a
map showing a Krückeberg property borders the indivudal at this site.

=== Given Name not Used

Also note this NOTE on xref:petzen:PET-B-1744a.adoc[]:

[NOTE]
====
The baptism of a Johann Heinrich Krückeberg does not list the father's given names.
It says only "Krückeberg aus Berenbusch", which suggests there might only be one
Krückeberg family in Berenbusch? While most records on the same page mention the
father's given name, at least one other baptsim record on the same page likewise only
mentions the surname. There are records on the prior page where only the surname is
mentioned, too.
====

=== rg "Wilharm"

Do: `rg 'Wilharm; *.adoc. Note the results show that both branches of the Krückebergs seem
to have Wilharms as baptism sponsors. We know from NLA 146, doc #1, that Jobst Heinrich
Krückeberg and his family lived at the Wilharms as tenants.

=== Key

Work from known to unknow, from most recent to prior generation methodically.

=== Other Petzen Records to Review

See manilla folder

=== Follow FamilySearch Leads

The parents of Anne Maria Margarethe Vahlsing, who married Johann Heinrich Krückeberg on 28 Sep. 1727 in
Petzen (see xref:petzen:PET-M-1727a.adoc[]) are given on FamilySearch along with they were baptized and
into which parish. Their death dates are also given.

Following these other families may help uncover more information like aid in identifying the exact baptism
sponsors....but the Vahlsing's only appear once as baptism sponsors?

=== Summary

This information plus information from the NLA case files might really help. We know from NLA 146:
* Jobst Heinrich's father was a *Ackervogt*, someone who was usually experienced in farming.
What else do we know?
* Was his father an Einlieger?

=== Key

Always establish facts from the most recent back before the going back a generation.

Use FAN principle to research spouses lineage, again from more recent to least recent.

== Research Item to Add

=== Also Add Carl Friedrich Bleeke Military Service

Add/create background information for Carl Friedrich Bleeke using his Iowa tombstone and his known residence in
LEteln/Frill area. Add this to the research page, stating we would like any of his military records.

== Background Sources to Read to Better Understand Schaumburg-Lippe

[arabic,start=1]
. link:https://de.wikipedia.org/wiki/Anerbenrecht[Anerbenrecht]
. link:https://www.histag-schaumburg.de/page/page_ID/111[Historiche Arbetisgemeinschaft für Schaumburg]
. link:https://de.wikipedia.org/wiki/Schaumburg-Lippe[Schaumburg-Lippe]
. link:https://catalog.hathitrust.org/Record/002200458?type%5B%5D=all&lookfor%5B%5D=Schaumburg-Lippe[Die landwirtschaftlichen Verhältnisse und die Agrarreformen in Schaumburg-Lippe im 18. und 19. Jahrhundert /
von Karl Heinz Schneider.]
. https://www.ekomp.digihist.de/Dokumentation_Datensaetze/Multimedia/Staaten/Schaumburg-Lippe.pdf

=== Scan Book: "Die landwirtschaftlichen Verhältnisse und die Agrarreformen in Schaumburg-Lippe im 18. und 19.  Jahrhundert / von Karl Heinz Schneider."

So that I can have it translated by Deepl.

== Finish Converting Dr Moehle's Report to AsciiDoc

The report is in `~/gen/m/background/pages/report_moehle.adoc`. Convert its em dashes to AsciiDoc '--'.

Use "--" for em dashesm and for en dashes, follow these steps:

. Put this at the top of the file: `:ndash: –`.
. Use it like this: `1798{ndash}1800`.

Also:
* correct grammar.

Use Gemini or Chatgpt to rewrite it.

== Andrea Bentschneider's German Emigration Video Series

url:
https://members.germangenealogycollective.com/courses/products/86a4a680-fcb7-463c-93c1-d9db7bda624e/categories/5bb1eb4a-bf08-4436-adf7-fdfb55326aef/posts/7bbc8283-f8c8-4a67-9554-2c7f6d9735c0?courses=my&source=courses

=== Event Table Changes

1. Rename the Residence/Village column to: Residence / Village +
(Bap./Conf.)

2. Rework all the event tables to follow the Usage Notes in `event-tables.adoc#usage-notes`.

3. Use Event Codes

=== Carl Friedrich Family of Origin

Add his wife's baptism and confirmation records.

== Add Nachtraege for jhk-1744-events.adoc

== Research Questions

=== Orphaned Children of JHK 1704

If Johann Heinrich Krückeberg (1704-1759) died in 1759, and if he was the father of those
children born between 1728 and 1750, then his children became orphans because Johann Heinrich Krückeberg's
wife died two years before him.

Where and with whom did they live? Do Confirmation records tell us?

xref:petzen:PET-C-1764a[] tells us he live in Berenbusch. He was born in 1750: xref:petzen:PET-B-1750a.adoc[].

=== Baptism Records to Find

* The 3rd wife of Johann Heinrich Krückeberg, Philippine Doroth[ea] Beucken, was an Einliegerin from Evesen.
Find her birth record from circa 1765.

* On FamilySearch, Anne Marie Philippine Krückeberg, born 1795, shown to be the child of Johann Heinrich Krückeberg
(from Berenbusch) and Philippine Dorothea Beucken. The citation given is: https://familysearch.org/ark:/61903/1:1:VH7C-TCF

Yet that record's spelling of the mother's surname is different; it is *Boecker*.

The original Dankersen, Kreis Minden, parish Kirchenbücher are on Archion.de: https://www.archion.de/p/fe0c680d5c/

=== Add to Jobst-h-krueckeberg-1779.adoc...

Mention that Jobst Heinrich had only one wife. Cite the case file in support and any Nachtraege and mention that
rarety of divorce.

=== Did Johann Heinrich born in 1744 Marry at age 17 in 1761?

That is what is one family search.

=== Who is the Johann Heinrich Who Died in 1759?

He died at age 55? See xref:petzen:PET-D-1759a.adoc[].
Answer: The Johann Heinrich who married in 1727.

== Add Nachtra'eg to jhk-1767-events.adoc

Go through the family records and add the nachtra'ge.

== Work on this new Record

Add the record to my website and Johann Heinrich's event tree:
https://dfg-viewer.de/show?tx_dlf%5Bdouble%5D=0&tx_dlf%5Bid%5D=https%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Ostwestfalen-Lippe%2FP1%2FB%2F~001%2FB00168_02_1831-1845%2Fmets.xml&tx_dlf%5Bpage%5D=40&cHash=7d66b09b1bf2d80b14084deb862675d3

Then correct FamilySearch id P35C-TTV, after I determine which Johann Heinrich is her father.

== Change Citations for Frille Kirchenbuchduplikat

Change the FRI-*-182??.adoc and FRI-*-183>>.adoc file from what I have not to match the format of `FRI-M-1826a.adoc`.

== Research

Find the death of Philippine Caroline Christine Krückeberg's 1st husband, since she
remarried, according to the Nachtaege in her baptism record, PET-B-1792a.adoc, on
11 May 1834, after first marrying on 23 Feb. 1812.

== Rewrite or Eliminate `m/research/johann-hinrich-krueckeberg`

I believe it is out of date. The "issues" paragraph at the end is good.
It mentions that there are other birth records from the 1728 to 1750 timeframe that also 
only mentioned the father's surname.

== New Research Question

See `m/research/p/did-jhk-1744-marry-at-17.adoc`.

== Is cfk-family-events is too long?

Perhaps put some of the text into a intro page? 

== Research Question

For the k r u e c k e b e r marriage in 1727 and the subsequent children with that surname that were born in whose
records the parentage is given either as k r u e c k e b e r g from b e r e n Busch, or Johann Heinrich k r u e c k
e b e r g. Are these one in the same person? Is the person with Justice surname and without a given name one in the
same as Johann Heinrich?

== Xref's

On `m/research/bueckeburg-archive-research.adoc`. provide xref's to individuals page that lists
the source of the info.

== Pedigree/Ancestry instead of Event Tables

Rename the Event Tables module to *ancestry* and within it use the event-tables'
pages. Add .svg images of the ancestry. Group the pages by one or two generations.

== Tools for Generating Family Trees

See: https://chatgpt.com/share/692cd231-6ac8-8004-93e0-b34ac18795f6

== Event Tables TODOES

* Confirm the accuracy of the combined event table.
* Merge into it the Petzen birth, baptism and confirmation records for Carl Friedrich Krückeberg 
and his wife.

== Research: In the early Petzen church registers, find all remaining records

Find all remaing Krueckeberg birth/bpatims, possible donfirmation, marriage and deathj/burial records.

Using the hand written lists of Archion.de images I have reviewed and have yet to review:

* Find any remaining births between 1746/image 174 and 1750/image 180 that were missed. <--DONE!!
* Continue on with my handwritten inventory of images I have reviewed.
* Also deaths during the time period 1728 to 1750
* Marriages between 1710 to 1750.

== "Other" section to website

Put modules that have been commented out and navigation that has been commented out, like 
*Helpful Background information* in `m/research/nav.adoc` under a new"Other" category.

== CRON Job for Building Website 

CRON job:

----
0 3 * * * cd /home/kurt/antora-genealogy && git pull
0 3 * * * cd /home/kurt/nla-documents && git pull
5 3 * * * cd /home/kurt/antora-site && antora antora-playbook.yml
----

This will:
* 3:00 AM → update genealogy repo
* 3:00 AM → update nla repo
* 3:05 AM → rebuild website

== Krückeberg and a Map Showing Krückeberg Property is Mentioned in Case File ????

Find this <----------
I know there was a map/drawing of Berenbusch showing a "Krückeberg" Stätte in Berenbusch.

== Add Citations to Immanuel Lutheran Bios

See `~/imm/citations.adoc` for guidance. I need to figure out on which image number each bio appears.

== Questions Concerning No. 10 Berenbusch

Was it created during the course of the Rentkammer reviewing case file #143? Here is its
archive information:

[cols="2,3,1"]
|===
|Identifier/Call #er|Description|Time Frame

|NLA BU, K 2, B Nr. 143	
|Die Stätte Nr. 14 zu Berenbusch
|1783 - 1792
|===


== Research Plan for Petzen Krückeberg Records

As to analyzing who fathered the 1728-1750 Kruekeberg chilren, see
https://chatgpt.com/share/691fa228-7674-8004-91a5-1bf305719fb1 and
xref:./modules/ancestry/pages/design-strategy.adoc[Design Strategy] on how to 
create an event table.

Start with the more recent records use the biography of Johann Heinrich and trhe biography of Carl
Heinrich Wilhelm Krückeberg along with his father's _Familienschein des Auswanderers Carl Friedrich
Krueckeberg_, and then begin to use the church records. As the link above suggest create a table by
house number. 

Perhaps also later use this information to create some sort of a configuration file that will display a tree. And a
timeline with record sources for each individual.
`
=== Birth Records Parentage Patterns and Statistics

|===
|Birth Date|Child|Parentage Description|Instances of Surname-only Parentage on the same and adjacent pages

|
|
|
|
|===

=== The naming pattern is also important. Look for first born grandsons that have the paternal grandfather's name

If there were a Jobst second contemporary Krückeberg who also fathered children. If those children
later married or were confirmed possibly confirmed might have the father's name or later died, then they're
marriage should have the full father's name, and perhaps confirmation and death records, too.

of Johann Heinrich. This would involve looking at sons of the Johann Heinrich who was born in 1704 and then 
looking for marriages of those sons and seeing if their sons, the grandsons of the prospective grandfather
Johann Heinrich, had his given name.

=== Pattern of Baptism Sponsors

If we can find only one Krückeberg living in Berenbusch through secular records when these births occurred, then we
will have eliminated the possibility of an jobst being a different person.

=== Only Other Patterns

== Pedigree of Johann Heinrich, born 1806

Immanuel bio plus initial U.S. records, then onto the Petzen church records.

