= TODO

== TODO Next

Finish what I began in m/background/stand-meaning.adoc and the other .adoc files
in m/background/p/underdevelopment.

== Baptism Birthplace Records Wrong?

Are some baptism's birthplaces wrong?

In baptism entries for two of the children of Carl Friedrich Gottlieb
Krückeberg we have two different birthplaces given--or are these no
birthplaces but current residences?  The birthplace for Carl Friedrich
born in 1807 and the daughter born the next year is given only as
"Berenbusch". In these records, there is a column for the "Name, Stand,
Religion and Birthplace of the Father". However, for the 1807 birth of
Carl Friedrich, this column contains "Carl Friedrich Gottlieb Krückeberg.
Schneider u. Einlieger in n. 14 in Bärenbusch. Luth. Conf.", while for the
the 1812 birth of daughter Carloline Dorothee Krückeberg it has "Carl
Friedrich Gottlieb Krückeberg n. 18 in Bärenbusch Luth. Conf.".

So is "n. 14 Berenbsuch" and "n. 18 Berenbusch" the address at the time
the child was born despite the column stating it is the "birthplace of the
father"? The actual birth record of Carl Friedrich Gottlieb is of no help
in answering this question since it only mentions Berenbusch.  

Answer: The answer is given in the column "Wohnort der Eltern", which
has the same address as that of the father.

== What 146 Tells Us

I tells us that Jobst Heinrich's father was an Ackervogt in Arensburg, which was the 
area in Steinbergen as ChatGPT explained:

____
1. Arensburg was not originally a town name but referred to a local castle and administrative area
In the territory of the historical County/Principality of Schaumburg-Lippe, Arensburg referred primarily to a
castle (Schloss/Arensburg) and the surrounding Amt (administrative district) near the village of Steinbergen in
what is now the district of Schaumburg in Lower Saxony, Germany. This “Amt Arensburg” formed part of the
territorial structure of Schaumburg-Lippe along with other Ämter such as Bückeburg, Hagenburg, and Stadthagen
___

Would there be records for a Ackervogt in Steinbergen?

=== Read the Zotero Links in Schaumburg-Lippe

== Rewrite Dr. Moehle's Work

Should this material be merge with Dr. Moehle's work.

== Research to Do

=== Map

Look for NLA case file for a Berenbusch site that belongs to a non-Krueckeberg that contains a
map showing a Krückeberg property borders the indivudal at this site.

=== Given Name not Used

Also note this NOTE on xref:petzen:PET-B-1744a.adoc[]:

[NOTE]
====
The baptism of a Johann Heinrich Krückeberg does not list the father's given names.
It says only "Krückeberg aus Berenbusch", which suggests there might only be one
Krückeberg family in Berenbusch? While most records on the same page mention the
father's given name, at least one other baptsim record on the same page likewise only
mentions the surname. There are records on the prior page where only the surname is
mentioned, too.
====

=== rg "Wilharm"

Do: `rg 'Wilharm; *.adoc. Note the results show that both branches of the Krückebergs seem
to have Wilharms as baptism sponsors. We know from NLA 146, doc #1, that Jobst Heinrich
Krückeberg and his family lived at the Wilharms as tenants.

=== Key

Work from known to unknow, from most recent to prior generation methodically.

=== Other Petzen Records to Review

See manilla folder

=== Follow FamilySearch Leads

The parents of Anne Maria Margarethe Vahlsing, who married Johann Heinrich Krückeberg on 28 Sep. 1727 in
Petzen (see xref:petzen:PET-M-1727a.adoc[]) are given on FamilySearch along with they were baptized and
into which parish. Their death dates are also given.

Following these other families may help uncover more information like aid in identifying the exact baptism
sponsors....but the Vahlsing's only appear once as baptism sponsors?

=== Summary

This information plus information from the NLA case files might really help. We know from NLA 146:
* Jobst Heinrich's father was a *Ackervogt*, someone who was usually experienced in farming.
What else do we know?
* Was his father an Einlieger?

=== Key

Always establish facts from the most recent back before the going back a generation.

Use FAN principle to research spouses lineage, again from more recent to least recent.

== Research Item to Add

=== Also Add Carl Friedrich Bleeke Military Service

Add/create background information for Carl Friedrich Bleeke using his Iowa tombstone and his known residence in
LEteln/Frill area. Add this to the research page, stating we would like any of his military records.

== Background Sources to Read to Better Understand Schaumburg-Lippe

[arabic,start=1]
. link:https://de.wikipedia.org/wiki/Anerbenrecht[Anerbenrecht]
. link:https://www.histag-schaumburg.de/page/page_ID/111[Historiche Arbetisgemeinschaft für Schaumburg]
. link:https://de.wikipedia.org/wiki/Schaumburg-Lippe[Schaumburg-Lippe]
. link:https://catalog.hathitrust.org/Record/002200458?type%5B%5D=all&lookfor%5B%5D=Schaumburg-Lippe[Die landwirtschaftlichen Verhältnisse und die Agrarreformen in Schaumburg-Lippe im 18. und 19. Jahrhundert /
von Karl Heinz Schneider.]
. https://www.ekomp.digihist.de/Dokumentation_Datensaetze/Multimedia/Staaten/Schaumburg-Lippe.pdf

=== Scan Book: "Die landwirtschaftlichen Verhältnisse und die Agrarreformen in Schaumburg-Lippe im 18. und 19.  Jahrhundert / von Karl Heinz Schneider."

So that I can have it translated by Deepl.

== Finish Converting Dr Moehle's Report to AsciiDoc

The report is in `~/gen/m/background/pages/report_moehle.adoc`. Convert its em dashes to AsciiDoc '--'.

Use "--" for em dashesm and for en dashes, follow these steps:

. Put this at the top of the file: `:ndash: –`.
. Use it like this: `1798{ndash}1800`.

Also:
* correct grammar.

Use Gemini or Chatgpt to rewrite it.

== Andrea Bentschneider's German Emigration Video Series

url:
https://members.germangenealogycollective.com/courses/products/86a4a680-fcb7-463c-93c1-d9db7bda624e/categories/5bb1eb4a-bf08-4436-adf7-fdfb55326aef/posts/7bbc8283-f8c8-4a67-9554-2c7f6d9735c0?courses=my&source=courses

=== Event Table Changes

1. Rename the Residence/Village column to: Residence / Village +
(Bap./Conf.)

2. Rework all the event tables to follow the Usage Notes in `event-tables.adoc#usage-notes`.

3. Use Event Codes

=== Carl Friedrich Family of Origin

Add his wife's baptism and confirmation records.

== Add Nachtraege for jhk-1744-events.adoc

== Research Questions

=== Orphaned Children of JHK 1704

If Johann Heinrich Krückeberg (1704-1759) died in 1759, and if he was the father of those
children born between 1728 and 1750, then his children became orphans because Johann Heinrich Krückeberg's
wife died two years before him.

Where and with whom did they live? Do Confirmation records tell us?

xref:petzen:PET-C-1764a[] tells us he live in Berenbusch. He was born in 1750: xref:petzen:PET-B-1750a.adoc[].

=== Baptism Records to Find

* The 3rd wife of Johann Heinrich Krückeberg, Philippine Doroth[ea] Beucken, was an Einliegerin from Evesen.
Find her birth record from circa 1765.

* On FamilySearch, Anne Marie Philippine Krückeberg, born 1795, shown to be the child of Johann Heinrich Krückeberg
(from Berenbusch) and Philippine Dorothea Beucken. The citation given is: https://familysearch.org/ark:/61903/1:1:VH7C-TCF

Yet that record's spelling of the mother's surname is different; it is *Boecker*.

The original Dankersen, Kreis Minden, parish Kirchenbücher are on Archion.de: https://www.archion.de/p/fe0c680d5c/

=== Add to Jobst-h-krueckeberg-1779.adoc...

Mention that Jobst Heinrich had only one wife. Cite the case file in support and any Nachtraege and mention that
rarety of divorce.

=== Did Johann Heinrich born in 1744 Marry at age 17 in 1761?

That is what is one family search.

=== Who is the Johann Heinrich Who Died in 1759?

He died at age 55? See xref:petzen:PET-D-1759a.adoc[].
Answer: The Johann Heinrich who married in 1727.

== Add Nachtra'eg to jhk-1767-events.adoc

Go through the family records and add the nachtra'ge.

== Work on this new Record

Add the record to my website and Johann Heinrich's event tree:
https://dfg-viewer.de/show?tx_dlf%5Bdouble%5D=0&tx_dlf%5Bid%5D=https%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Ostwestfalen-Lippe%2FP1%2FB%2F~001%2FB00168_02_1831-1845%2Fmets.xml&tx_dlf%5Bpage%5D=40&cHash=7d66b09b1bf2d80b14084deb862675d3

Then correct FamilySearch id P35C-TTV, after I determine which Johann Heinrich is her father.

== Change Citations for Frille Kirchenbuchduplikat

Change the FRI-*-182??.adoc and FRI-*-183>>.adoc file from what I have not to match the format of `FRI-M-1826a.adoc`.

== Research

Find the death of Philippine Caroline Christine Krückeberg's 1st husband, since she
remarried, according to the Nachtaege in her baptism record, PET-B-1792a.adoc, on
11 May 1834, after first marrying on 23 Feb. 1812.

== Rewrite or Eliminate `m/research/johann-hinrich-krueckeberg`

I believe it is out of date. The "issues" paragraph at the end is good.
It mentions that there are other birth records from the 1728 to 1750 timeframe that also 
only mentioned the father's surname.

== New Research Question

See `m/research/p/did-jhk-1744-marry-at-17.adoc`.

== Is cfk-family-events is too long?

Perhaps put some of the text into a intro page? 

== Research Question

For the k r u e c k e b e r marriage in 1727 and the subsequent children with that surname that were born in whose
records the parentage is given either as k r u e c k e b e r g from b e r e n Busch, or Johann Heinrich k r u e c k
e b e r g. Are these one in the same person? Is the person with Justice surname and without a given name one in the
same as Johann Heinrich?

== Xref's

On `m/research/bueckeburg-archive-research.adoc`. provide xref's to individuals page that lists
the source of the info.

== Pedigree/Ancestry instead of Event Tables

Rename the Event Tables module to *ancestry* and within it use the event-tables'
pages. Add .svg images of the ancestry. Group the pages by one or two generations.

== Tools for Generating Family Trees

See: https://chatgpt.com/share/692cd231-6ac8-8004-93e0-b34ac18795f6

== Event Tables TODOES

* Confirm the accuracy of the combined event table.
* Merge into it the Petzen birth, baptism and confirmation records for Carl Friedrich Krückeberg 
and his wife.

== Research: In the early Petzen church registers, find all remaining records

Find all remaing Krueckeberg birth/bpatims, possible donfirmation, marriage and deathj/burial records.

Using the hand written lists of Archion.de images I have reviewed and have yet to review:

* Find any remaining births between 1746/image 174 and 1750/image 180 that were missed. <--DONE!!
* Continue on with my handwritten inventory of images I have reviewed.
* Also deaths during the time period 1728 to 1750
* Marriages between 1710 to 1750.

== "Other" section to website

Put modules that have been commented out and navigation that has been commented out, like 
*Helpful Background information* in `m/research/nav.adoc` under a new"Other" category.

== CRON Job for Building Website 

CRON job:

----
0 3 * * * cd /home/kurt/antora-genealogy && git pull
0 3 * * * cd /home/kurt/nla-documents && git pull
5 3 * * * cd /home/kurt/antora-site && antora antora-playbook.yml
----

This will:
* 3:00 AM → update genealogy repo
* 3:00 AM → update nla repo
* 3:05 AM → rebuild website

== Krückeberg and a Map Showing Krückeberg Property is Mentioned in Case File ????

Find this <----------
I know there was a map/drawing of Berenbusch showing a "Krückeberg" Stätte in Berenbusch.

== Add Citations to Immanuel Lutheran Bios

See `~/imm/citations.adoc` for guidance. I need to figure out on which image number each bio appears.

== Questions Concerning No. 10 Berenbusch

Was it created during the course of the Rentkammer reviewing case file #143? Here is its
archive information:

[cols="2,3,1"]
|===
|Identifier/Call #er|Description|Time Frame

|NLA BU, K 2, B Nr. 143	
|Die Stätte Nr. 14 zu Berenbusch
|1783 - 1792
|===


== Research Plan for Petzen Krückeberg Records

As to analyzing who fathered the 1728-1750 Kruekeberg chilren, see
https://chatgpt.com/share/691fa228-7674-8004-91a5-1bf305719fb1 and
xref:./modules/ancestry/pages/design-strategy.adoc[Design Strategy] on how to 
create an event table.

Start with the more recent records use the biography of Johann Heinrich and trhe biography of Carl
Heinrich Wilhelm Krückeberg along with his father's _Familienschein des Auswanderers Carl Friedrich
Krueckeberg_, and then begin to use the church records. As the link above suggest create a table by
house number. 

Perhaps also later use this information to create some sort of a configuration file that will display a tree. And a
timeline with record sources for each individual.
`
=== Birth Records Parentage Patterns and Statistics

|===
|Birth Date|Child|Parentage Description|Instances of Surname-only Parentage on the same and adjacent pages

|
|===

=== The naming pattern is also important. Look for first born grandsons that have the paternal grandfather's name

If there were a Jobst second contemporary Krückeberg who also fathered children. If those children
later married or were confirmed possibly confirmed might have the father's name or later died, then they're
marriage should have the full father's name, and perhaps confirmation and death records, too.

of Johann Heinrich. This would involve looking at sons of the Johann Heinrich who was born in 1704 and then 
looking for marriages of those sons and seeing if their sons, the grandsons of the prospective grandfather
Johann Heinrich, had his given name.

=== Pattern of Baptism Sponsors

If we can find only one Krückeberg living in Berenbusch through secular records when these births occurred, then we
will have eliminated the possibility of an jobst being a different person.

=== Only Other Patterns

== Pedigree of Johann Heinrich, born 1806

Immanuel bio plus initial U.S. records, then onto the Petzen church records.

