= TODO

== Update the Citation Anchors to Reflect the New File Names


== Research Plan

As to analyzing who fathered the 1728-1750 Kruekeberg chilren, see
https://chatgpt.com/share/691fa228-7674-8004-91a5-1bf305719fb1: 

Start with the more recent records use the biography and the family record of my three times great-grandfather and
then begin to use the church records. As the link above suggest create a table by house number. The suggestions. I
can use this information to create some sort of a configuration file that will display a tree. And a timeline with
record sources for each individual.

See also: ./modules/ancestry/pages/design-strategy.adoc

=== Find All Remaining Records

Using the lists of Archion.de images I have reviewed and have yet to review:

[IMPORTANT]
====
* --> Find any remaining births between 1746 and 1750 that were missed. <--
* Also deaths during the time period 1728 to 1750
* Marriages between 1710 to 1750.
====

=== Birth Records Parentage Patterns and Statistics

|===
|Birth Date|Child|Parentage Description|Instances of Surname-only Parentage on the same and adjacent pages

|
|===

=== The naming pattern is also important. Look for first born grandsons that have the paternal grandfather's name

If there were a Jobst second contemporary Krückeberg who also fathered children. If those children
later married or were confirmed possibly confirmed might have the father's name or later died, then they're
marriage should have the full father's name, and perhaps confirmation and death records, too.

of Johann Heinrich. This would involve looking at sons of the Johann Heinrich who was born in 1704 and then 
looking for marriages of those sons and seeing if their sons, the grandsons of the prospective grandfather
Johann Heinrich, had his given name.

=== Pattern of Baptism Sponsors

If we can find only one Krückeberg living in Berenbusch through secular records when these births occurred, then we
will have eliminated the possibility of an jobst being a different person.

=== Only Other Patterns

== Pedigree of Johann Heinrich, born 1806

Immanuel bio plus initial U.S. records, then onto the Petzen church records.

