= TODO

= Tools for Generating Family Trees

Graphviz and Mermaid. See https://chatgpt.com/share/692cd231-6ac8-8004-93e0-b34ac18795f6.

== Event Tables TODOES

* Confirm the accuracy of the combined event table.
* Merge into it the Petzen birth, baptism and confirmation records for Carl Friedrich Krückeberg 
and his wife.

== Research: In the early Petzen church registers, find all remaining records

Find all remaing Krueckeberg birth/bpatims, possible donfirmation, marriage and deathj/burial records.

Using the hand written lists of Archion.de images I have reviewed and have yet to review:

* Find any remaining births between 1746/image 174 and 1750/image 180 that were missed. <--DONE!!
* Continue on with my handwritten inventory of images I have reviewed.
* Also deaths during the time period 1728 to 1750
* Marriages between 1710 to 1750.

== "Other" section to website

Put modules that have been commented out and navigation that has been commented out, like 
*Helpful Background information* in `m/research/nav.adoc` under a new"Other" category.

== CRON Job for Building Website 

CRON job:

----
0 3 * * * cd /home/kurt/antora-genealogy && git pull
0 3 * * * cd /home/kurt/nla-documents && git pull
5 3 * * * cd /home/kurt/antora-site && antora antora-playbook.yml
----

This will:
* 3:00 AM → update genealogy repo
* 3:00 AM → update nla repo
* 3:05 AM → rebuild website

== Krückeberg and a Map Showing Krückeberg Property is Mentioned in Case File ????

Find this <----------
I know there was a map/drawing of Berenbusch showing a "Krückeberg" Stätte in Berenbusch.

== Add Citations to Immanuel Lutheran Bios

See `~/imm/citations.adoc` for guidance. I need to figure out on which image number each bio appears.

== Questions Concerning No. 10 Berenbusch

Was it created during the course of the Rentkammer reviewing case file #143? Here is its
archive information:

[cols="2,3,1"]
|===
|Identifier/Call #er|Description|Time Frame

|NLA BU, K 2, B Nr. 143	
|Die Stätte Nr. 14 zu Berenbusch
|1783 - 1792
|===


== Research Plan for Petzen Krückeberg Records

As to analyzing who fathered the 1728-1750 Kruekeberg chilren, see
https://chatgpt.com/share/691fa228-7674-8004-91a5-1bf305719fb1 and
xref:./modules/ancestry/pages/design-strategy.adoc[Design Strategy] on how to 
create an event table.

Start with the more recent records use the biography of Johann Heinrich and trhe biography of Carl
Heinrich Wilhelm Krückeberg along with his father's _Familienschein des Auswanderers Carl Friedrich
Krueckeberg_, and then begin to use the church records. As the link above suggest create a table by
house number. 

Perhaps also later use this information to create some sort of a configuration file that will display a tree. And a
timeline with record sources for each individual.
`
=== Birth Records Parentage Patterns and Statistics

|===
|Birth Date|Child|Parentage Description|Instances of Surname-only Parentage on the same and adjacent pages

|
|===

=== The naming pattern is also important. Look for first born grandsons that have the paternal grandfather's name

If there were a Jobst second contemporary Krückeberg who also fathered children. If those children
later married or were confirmed possibly confirmed might have the father's name or later died, then they're
marriage should have the full father's name, and perhaps confirmation and death records, too.

of Johann Heinrich. This would involve looking at sons of the Johann Heinrich who was born in 1704 and then 
looking for marriages of those sons and seeing if their sons, the grandsons of the prospective grandfather
Johann Heinrich, had his given name.

=== Pattern of Baptism Sponsors

If we can find only one Krückeberg living in Berenbusch through secular records when these births occurred, then we
will have eliminated the possibility of an jobst being a different person.

=== Only Other Patterns

== Pedigree of Johann Heinrich, born 1806

Immanuel bio plus initial U.S. records, then onto the Petzen church records.

