= Bleeke Background

== Birthplace

Johann Heinrich Philipp Bleeke's Immanel Lutheran xref:immanuel-lutheran:DEC-BIO-Bleeke-01.adoc[biography] summarizes his parentage, marriage, children
and how he came to Union twp, Adams, Indiana. It explains he was born 

"zu Leeteln (Leteln), Kanton Windheim, Kreis Minden, Königr. Preussen"
-- Immanuel Luthern, Decautur, biogrpahy for J.H.P. Bleeke

== New Facts about Bleekes in Leteln Revealed

In December 2013 the _Heimatpfleger_ (local history or hertitage curator) of Leteln, link:http://www.sturma-online.de[Jürgen Sturma], wrote an important
article about the <<leitler-blatt, history of the Leteln school>> the <<leitler-blatt, and the Bleeke family's connection to it>> that revealed previously
unknown facts about the Bleekes. The article (in German) is available as a PDF file link:http://www.sturma-online.de/styled-29/styled/downloads-2/files/Leitler%20Blatt%202013-1.pdf[online].

=== What is a Heimatfpleger?

Jurgen Stürma link:http://www.sturma-online.de[describes a Heimatpfleger] as a type local heritage custodian:

[quote, Heimatpfleger]
____
Heimatpflegers (Heritage custodians) are mostly volunteers and officially appointed persons who are involved in heritage preservation and similar areas
in their area of responsibility. They advise and support districts and independent towns, municipalities, museums, associations, schools, churches and
private individuals. They can be members of specialist committees of public administrations and often run a heritage association themselves. The term
"Heimatpfleger" was established by Otto Merkt.

A general distinction is made between full-time district heritage officers and honorary district heritage officers, town or local heritage officers.
The respective guidelines for local historians differ depending on the federal state.
____

== Translation of Jurgen Stürma's December 2013 Articles 

[#juergen_article_anchor]
=== The Leteln School has come to an end after almost 400 years.

Since the 17th century there had been a school in Leteln, which was supported by the farmers' associations
of Leteln and Aminghausen. Classes took place in various buildings in Leteln.

On one of the last village visits, the participants (members of the Heimatsverein?)
were astonished to discover that even before 1686 there had been a schoolmaster and a
school in Leteln. This is evident from the entries in the Frille church book.

The first of these schoolmasters was buried on 25 August 1686 at the age of about 50 years:

.Excerpt from the Frille church register:
[quote]
Claus Pennigroth, who was schoolmaster in Leteln on 25 August 1686, was buried at the age of 50

The location of the Leteln school remains unknown. From about 1703 onward the Bleeke (or Bleke
as it often appears in the church register) "schoolmaster dynasty" provided the teachers for Leteln.

The Bleeke family came from **Ilser Heide** (Ilserheide), as the pastor of Frille refers
to it, and provided not only the teachers for Leteln, but also some of
the Frille teachers or schoolmasters and sextons.

The relationship between these families remains unclear for the time being, as the relevant data
from the church records have not yet been evaluated. Since many of the birth dates cannot be found
in the Frille church register, one must assume that some of the Leteln school masters Bleeke were
not always father and son.

Up to 1800, nine Leteln schoolmasters are mentioned in the Frille
church records.

[arabic]
. Claus Pennigroth, approximately 1636. Died August 1686.
. Johann Hermann Siechmann, approximately 1664. Died 1692.
. Christian Bürgius is mentioned in the Frille church book in 1696 as
schoolmaster in Leteln, because he had his son Arend Heinrich baptized
in April of that year.
. Johann Heinrich Kruse, schoolmaster in Leteln, marries Catharina
Deerberg on 3 June 1688. He is buried on January 7, 1703, according to
the church register.
. **Hans Heinrich Bleeke** from Ilserheide, schoolmaster in Leteln, 13.
April 1681, marries Ilse Marie Deerberg from Aminghausen on 20 April 1703.
She was probably the widow of Jürgen Volkening from Leteln. In
1732, the Frille church register states that Hans Heinrich Bleeke,
schoolmaster emeritus from Leteln, lived in Wietersheim.
. **Hans Heinrich Bleeke**, schoolmaster in Leteln around 1677, married Anna
Margarethe Prange on 25 May 1727. He is buried in Frille on July 2,
1749.
. **Heinrich Philip Bleeke**, schoolmaster in Leteln about 1714, son of
Johann Heinrich Bleeke and Anna Baden, marries Catharina Margarethe
Niehus from Aminghausen, on 2 June 1735. He died in 1758 and was buried
in Frille on 8 January. It is expressly stated that he was schoolmaster
in Leteln for 26 years.
. **Carl Bleeke**, schoolmaster in Leteln, died in 1771 (the year of his
death is not recorded in the Frille church book).
. **Carl Friedrich Bleeke**, schoolmaster in Leteln, 18 March 1739, married
Anna Marie Riechmanns from Leteln on 23 November 1793, after the death
of the mother with whom he ran the school. He died on 1 January 1800
without heirs.

We do not know when the Leteln School was established and where it was
located at that time. However, since the time of the Bleeke family, the
school has most likely been located in house no. 13, because it can be
assumed that the school was located in the house of the schoolmaster.
House No. 13 was also known as the Bleeke[German: Bleeken] House. When
the last schoolmaster died, he bequeathed his property to a relative who
ran a farm at No. 13. So the school must have been somewhere else from
that time on at the latest. The assumption is that it was located on the
later site 24 (Korte, now Lindenhof) and perhaps it was established
there earlier. During renovation work a gate beam was found, the
inscription of which refers to the use of the building: "Where youth are
educated well, much good things are certainly done—M. Joh, Hinrich
Ernsting 1762". It hasn't been nresolved whether the gate beam
came into the building later, or whether the school was actually moved
to house no. 24 on the village square as early as 1762. What is certain
is that the house belonged to the municipality in 1829.

[arabic, start=10]
. Johann Hartwig Wehmeier, around 1777, probably did not start teaching
until 1801, when he came from Gohfeld, his wife Friederike Amalie Lucas
"from the salt well near Rehme", i.e. from the later Bad Oeynhausen.
Wehmeier died on 16 March 1851, where it is noted that he would have
celebrated his 50th professional anniversary that year. He was 74 years
old.

Under teacher Wehmeier the school was moved to the site No. 19, which
was at the time where the last Leteln school was located (Large Drift
Trift 50/52). The municipality bought the residential house of the farm
No. 19 (Rösener). The family had originally owned farm No. 6, but had
had to sell it due to economic difficulties. The new farm no. 19 was
also sold and the family emigrated to America in 1841. The free house
number was given to another farm (Niehüsers), as the school was tax-free
and therefore did not require a house or tax number. In the house of the
former farm not only the school took place, but also the teacher and his
family lived here. It is not known in which rooms the school class was
housed. The only thing that can be determined from the photos is that
the chamber compartment was obviously rebuilt, as the roof protruded
over the two-column truss of the floorboard end.

[arabic, start=11]
. Gustav Adolf Hollstein follows in the teaching service in Leteln. He
came from Halle and was married to Elise Charlotte Sophie Meier from
Minden. Hollstein died on 7 December 1861 at the age of 37 in Leteln.
. Teacher Büsching took over the teaching duties in Leteln, but because
he was too worldly for the Letelners because of his violin playing, he
left Leteln the following year.
. August Rosteck followed teacher Büsching. He came from Petershagen and
was married to Magdalena Gleichen. Her gravestone is still on the
cemetery at Letelner Heidweg.

Rosteck was very musical and also brought a violin. It is said that the
Letelners said, "Then we could have kept the other one!" August Rosteck
died on November 19, 1899, and lived for the last time in the
"Noll-Villa" in front of the canal underpass, which of course did not
exist at that time, since the canal was built later. In the Frille
church book, it is expressly noted: " N.B. he was a faithful teacher in
the villages of Leteln and Aminghausen for over 40 years, lived on the
banks of the Kohlenufer, only temporarily in Aminghausen.”

[#test2]
=== The Bleeke Family
As is already known, the Bleeke family, who came from Ilserheide, provided the Leteln schoolmasters for many
decades. With the death of Carl Friedrich Bleeke on January 1, 1800, the time of the Bleeken schoolmasters
ended. The family continued to live in Leteln and ran a farm on farm number 13, which was therefore nicknamed
“Bleeken” and later also moved to farm number 16. In 1834 the Bleekes emigrated to America.

In 1977 Pastor Lohmann received a letter from Mrs. Sue Bleeke of Decatur, Indiana, U.S., asking him to do
research on her husband's, Don Bleeke’s, ancestors. Since such a task requires a lot of time, my neighbors
and I offered to take on this task. Until 1902 Leteln belonged to the Frille Church. So we had to search there.

In 1648 the Thirty Years War was over. When peace and order had returned, the pastors in the parishes started
again to record births, marriages and deaths in a big book. Everything that had been there
before was destroyed where the soldiers had gone through. In Frille, the first book begins in 1662. When we
found the first Bleeke, it was a big surprise to me that house number 13 was there. That was our house
number! So the Bleeken had had our house.

The first entry was: Hans Heinrich Bleeke, schoolmaster in Leteln. In 1703 he married Ilse Margarethe Deerberg from Leteln.
That was the blacksmith shop, where "Im Gang No. 9" is now. Since there were only a few houses in the village of Leteln,
we can assume that she was the daughter of the blacksmith Deerberg. The school was probably already in number 13 back then.
The Bleeken must have been bright. They weren't just schoolmasters (they didn't say teachers back then) in Leteln. We found
the name in Frille (45 years schoolmaster), Lahde and Ilserheide. In Leteln, the position was always passed down from father
to son. The last Bleeken schoolmaster died on January 1, 1800. He probably had no children and took the heir from Ilserheide.
This was Christian Bleeke. He married Anne Margarethe Volkening from Leteln No. 2. He was born in 1753 and had three sons.
Karl married a Niemann from Todtenhausen, Phillip a Schwier from Wietersheim and
Friedrich a Krückeberg from Berenbusch. In 1834 Phillip went to America, and one year later his wife and six children also,
three boys and three girls. The youngest was born in 1833. Later the two brothers and one Krückeberg also went to America.

The individual mentioned at the beginning, Don Bleeke, is a descendant
of **Phillip Bleeke**(that is: Johann Heinrich Phillip Bleeke).
He founded the Lutheran Immanuel Church and School in Decatur in 1849. The
commemorative publication from Decatur for the 125th anniversary in 1974
was sent to me by Sue Bleeke. In 1986 Louis Bleeke visited us with his
wife Dolores. He too is a descendant of Phillip Bleeke. For him it was
an exciting to stand on the ground that his ancestors had worked.

The garden is still the same size and the long hedge is most likely
still planted by the Bleekes. When my grandfather bought the property in
1883, the hedge was already old. Unfortunately the old house was no
longer standing. It had burned down in 1894. I then showed him
Rommelmann's house, because this is what the old Bleeke's house might
have looked like; it was built in 1772. These Bleekes have become one
big family. As Louis told me, there is a family reunion every two years.
About 200 people gather there. They have no connection with the
descendants of the other two Bleeke brothers. I still have contact by
letter with Louis, he still speaks and writes German. In 1989 a
Krückeberg visited me, descendants of the Krückebergs from Berenbusch.
He also spoke German.

Louis had already written to the mayor of Minden in 1970 and asked for
research. He had given the letter to the registry office, and they sent
it to Frille. He did not get an answer. We found the letter in the
church register in Frille.

About the Bleekes in the United States. The Bleeke family from Leteln
emigrated to America like many others. In the New World, new
possibilities opened up. The Bleekes settled in Union, Adams County,
Indiana about 5 years after emigration and were quite successful there.
In 1974 the 125th anniversary of the church was celebrated in Decatur,
Indiana. On this occasion a small commemorative publication was
published, from which the following information is partly taken. The
Bleeke family is also mentioned in "History of Adams and Wells County,
Indiana".

The living conditions were more than modest for many rural inhabitants
in Germany and many decided to emigrate in order to find a new
livelihood and better living conditions for themselves and their
families. We had already heard that the three sons of the Bleeke family
and also a brother-in-law of the Bleeken brothers, a Krückeberg from
Berenbusch, emigrated to the United States in 1834. They were Carl
Friedrich Bleeke (*1794), Johann Heinrich Philp Bleeke (1797-1883) and
Christian Friedrich (*1800), who was married to Luise Eleonore
Krückeberg from Berenbusch No. 10. Before Phillip Bleeke came to 
Decatur, he settled with his family in Wheeling, where he lived until 1837.
Then he went to Cincinnati. From there he undertook a journey in
1838 to find a new place to settle. Finally he came to Adams County,
where he purchased land. In 1840 he returned to Cincinnati to get his
family, who arrived on November 27 of the same year. The journey was
more than very arduous. The roads were so muddy that the family was
eventually forced to leave part of their household in New Bremen, Ohio.
They eventually had to continue on foot and could only manage 5 miles a
day at most.

At first they all lived in a tent, which they had built out of the
tarpaulin of the wagon and a few strong wooden poles. During this time
they built themselves a primitive log cabin. On the 24th day December
they could finally move in. Only in 1852 they built the house, which
still stands in its old place.

The road to the church was 5 miles long, which the Bleekes always had to
walk. Finally, from 1849 on, the Bleekes' house was regularly used for
devotions and sermons by Pastor Fritze. This is how the Evangelical
Lutheran Immanuel Church was founded

The community was initially very small. With the bride of Christian
Bleeke there were only eight people. In the course of the next years
other settlers joined the community: Johann Krückeberg with his wife and
three daughters and Heinrich Wilhelm Weyland with his wife, son and
daughter. It is obvious that the families still knew each other from
their old homeland. Other families soon joined them: Grote (1852),
Reinking (1853), Thieme (1855), Krückeberg, Schamerloh, Koldewey,
Höriger, Rücklos (all before 1858) In 1865 a school was established, in
which 18 children were first taught.

In the history of Adams County written 1889, it says about Frederick
William Blakey (Friedrich Wilhelm Bleeke), the son of Johann Heinrich
Philip Bleeke, he was born in Prussia in 1825 and came to America with
his parents at the age of 10 years. In 1854 he married Mary Bevelheimer
from Pennsylvania. In 1889 there were still 9 children from this
marriage. He owned a total of 480 acres of land, that is about 192
hectares or about 768 acres. The brothers Friedrich and Christian lived
in the same house until 1870. In 1850, they founded a potash factory.
The hardwood resulting from the cultivation of the land was burned to
ashes, from which potash and other products were then made. The company
was named John II. Blakey. The ash products were also used in the
production of ceramics and the Bleeke brothers (Blaeky) very
successfully entered the ceramic production in 1880. The Bleekes were
the second settler family in the Uniuon Township.

Christian Bleeke owned 400 acres in 1889, about 160 hectares or 640
acres. Christian married Louise Fahlsing and after her early death Mary A.
Rupp. He had 3 children from his first marriage and 10 from the
second.

One has to keep in mind the enormous changes the emigrant families went
through. They came from an old half-timbered house with a small farm in
Leteln and became wealthy farmers and entrepreneurs in America. Who had
a farm of 640 acres in Leteln?


[bibliography]
== References

[[leitler-blatt]]
* [[[leitler-blatt]]] Leitler Blatt, December 2013, online PDF, (https://tinyurl.com/y6fxse94 : 10 November 2023)
