= Inter-Family Relationships

== Weiland and Krückeberg and Bleeke

According to his Immanuel Lutheran xref:immanuel-lutheran:DEC-BIO-Krueckeberg-01.adoc[biography], the baptismal sponsor for Johann Heinrich’s
eldest child, Caroline Philippine Dorathee, born February 27, 1834, in Germany, were:

* **Doratha Weÿland (Weiland)**
* Philippine Watermann
* Caroline Krückeberg. 

**Doratha Weÿland** might be the **Luise Dorothea Weiland** who will marry Carl Freidrich Krückeberg, Johann Heinrich Krückeberg first
cousin, later that same year on 16 November 1834.

The sponsor of his second child, also born in Germany, on August 22, 1835, was **Christine Bleeke**.

=== Heinrich Wilhelm Weiland (1815-1866) and Johann Heinrich Krückeberg (1806-1879)

Relationship facts: 

* Johann Heinrich Krückeberg married Heinrich Wilhelm Weiland's older sister, xref:Caroline Sophie Weiland (1808-1879).

* Their resepective families departed Bremen/Hamburg together on the same ship, the Orion, which arrived in NYC on 5 November 1849.

* The "main" witness (clarify what he was) of Heinrich Wilhelm Weilland's Last Will and Testament was Johann Heinrich Krückeberg.

* TODO: Check for:
**  immanuel bios
** Did they live in close proximaty according to the platt map of Union township?proximity in Union twp?
** Were they sponsors to each other's children?

=== Carl Friedrich Krückeberg (1807-185?) and Luise Dorothea Weiland (1811-1870)

Carl Friedrich Krückeberg (1807-185?) married Luise Dorothea Weiland (1811-1870) on 16 November 1834.

Question: What was Carl Friedrich's relatioship to Johann Heinrich?

== Bleeke and Krückeberg
