= Koldewei Background

Displayed belows is the content of this xref:attachment$koldewei-biographies.pdf[PDF],
originally a typewritten document about the descendents of Ludwig Koldewei. 
I received scans of the typewritten pages from Melvin Krueckeberg on March 16, 2025.
As to who wrote it, Mel said

[quote]
____
I think it was Edith Rose (Marvel) Kammer wife of Robert D Kammer via Gertude Reinking via Mary Koldewey b. 1881.
Enclosed are 2 pages of scans of Ludwig Koldewey If you would like more on the Koldeweys I might have it because of
Rose's research.
____

==  Ludwig Koldewei

Eventhough Christopher Columbus discovered America in 1492, it wasn't
until the early 1600s that young, adventurious Europeans travelling to
America to establish new homes.  The first colonists from England,
Netherlands, and other European countries settled along the East coast
from Massachusetts to the Virginias.

The German Adventurers had to clear land farther west in what is now
considered the Midwest--Pennsylvania, Ohio and Indiana. They came in
small groups from the same area in Germany, cleared the land, built crude
homes and churches and raised their families. Commodities from Germany
were scarce, and they had to learn many shells in order to survive. Also,
they eyes the soft moccasins which the Indians wore, and they began to
fashion some of their shoes accordingly.

When Ludwig Koldewei, son of Ludwig Kaldewei I, came to America from
his home at Hanover, Germany, he embarked at Bremen and arrived in New
York on November 28, 1856. He became a naturalized citizen of the United
States in the Adams County, Indiana circuit court on October 8, 1858, and
had to swear that he was no longer subservient to Ernst August, King of
Honover [sic] and promise his allegiance to the United States of America. He
bought an 80-acre farm in Union Township, Adams County, Ind. from James
Stevens, which stayed in the Koldewey name until 1961, when Clara Koldewey
sold it to Arnold Thieme. James Stevens had been given and granted this
80-acre parcel by President James Folk on May 10, 1848.

Ludwig Koldewei added another 40-acre parcel of land and formed this as
one unit. I remember that we always referred to this tract as the "other
place".  Ludwig and his bride, the former Sophie Thieman, raised their 10
children on this farm in their log cabinet. The logs were later covered
with wood boards. Then when son Louis was married, he raised the four of
us on this farm: Nora, Reinhold, (me) Mildred and Lewis.

All the little communities of Germans adhered to their respective low-
German dialects which had been spoken in their community in Germany. The
dialects in the different communities were all a little different, and
one could easily identify the speaker's community from his dialect. All
church services were conducted in the proper high German. I was confirmed
in German at the Immanuel Lutheran Church in 1930. The church was built
in 1891. Now, in 1992, they no longer have German services, although not
many years ago, they still had German services (in addition to the English
service) one Sunday a month.

When the colonists settled, they had to be very independent for there
were no stores, no newspapers. Ludwig Koldewei made a cobbler's bench on
which he added an awl and various sizes of lasts, so that he could repair
the family's shoes. He also made a 4½ foot tall shee repair stand, so
that he could repair different size shoes while he was standing. I use
both the cobbler's bench (which we use in our living room) and the stand-
ing repair tool when I give my "Old Shoe Talk" to different groups and
show old shoes for men, women and children which we collected during our
27 years in the shore business.

There were itinerant cobbler's who came occasionally to repair shoes,
They were cut hair, pull teeth and whatever odd jobs needed to be done.
always welcome, because they could delay the news and gossip from their
previous communities.

=== Page 2. Ludwig Koldewei (Continued)

By this time the "Koldewei" had been changed to Koldewey" and the
family statistics are as follows:

K.H. Ludwig Koldewey 1835-1905
Wife: Sophia Louisa Margaretha Thieman Koldewey 1841-1914
Children:
* Fred 1862-1937 (Wife - Amelia)
* Emma (Mrs. Fred Krueckeberg) 1863-
* Louise 1866-1887
* Caroline 1868-
* William 1870- (Wife Anna)
* Sophia 1872- (Mrs. Fred Grote)
* Mathilda 1878-1953
* Mary 1881-1910 (Mrs. Gustav Reinking)
* Louis 1886-1955 (Wife Clara Hoffman)

Life centered around the Lutheran communities. A German tradition that
prevailed into the 1940's was the New Year's eve "New Year's shooting",
whereby the young men from our church went on foot to the homes of the
single maidens in the church and repeated a long, German, memorized speech
including wishes of good health and romance. Then they would give a gun
salute and enter the home of their host for cookies and wine. It was a
good thing that they walked from house to house all night, or they would
have gotten extremely drunk. Reinhold only went with them once.

Two prominent men by the name of Koldewey are found in the American
College history books. The following is quoted in the "New Century Encu-
clopedia of Names":

"Koldewey - Karl Christian born an Buchen (heim), Hanover, Germany,
Hanover, Germany, October 26, 1837.  Died at Hamburg, Germany, May 18,
1908. German Arctic explorer. He undertook in 1868 the first polar
expedition to Spitzbergen and an expedition (1869-70) to eastern
Greenland, where he discovered the large Franz Josef Fjord.

"Koldewey - Robert, born at Blanburg, Germany, September 10, 1855.
Died at Berlin February 4, 1925. German archeologist.  In 1899 he
directed the German excavation at Babylon. Author of 'Investigation at
Assos' (1902-21) with others and 'Die Tempel in Babylon'.

Pamela Grapner has visited the Pergamon Museum several times and has
seen Karl's photograph. Also in 1091 Pam and I visited the museum and
took pictures of the Ishtar Gate which Robert Koldewey excavated in
Babylon. The Ishtar Gate of Babylon is today the main attraction of
the Pergamon Museum. The excavation, which took place by the Euphrates
River in Iraq was headed by Robert Koldewey from March 26, 1899, to
spring of 1917.

=== Lewis William Koldewey

Lewis W. Koldewey was born on the farm homestead near Decatur, Indiana,
on November 18, 1921. He attended the parochial elementary school by the
Immanuel Lutheran Church, as we other three children had, and gradual
from Decatur High School in 1940, where he was editor of the high school
year book with a major in journalist, and a star catcher for the high
school baseball team. This athletic distinction gave him a one-year
scholarship to Indiana Central College in 1941. After his year at
College, he worked in Decatur at a service station in order to save
enough money to continue college. However, he foresaw the imminence of
world War II, so he registered for Service and entered the army on July
1, 1942. He was on officer in the field artillery in 1943; he took
pilot training and became an observation pilot; he was the writer for
the camp military and played baseball and football for the army. He
suffered from battalion ears and was given a medical discharge from
the army with the rank of lieutenant.

Lewis enrolled at Valparaiso University near Chicago and again disting-
wished himself with his athletic prowess. He was president of his senior
class, as well as president of his fraternity. He gradualed with a Juris
doctor of law degree.

While at Valparaiso, Lewis was very much attracted to a little fresh-
man girl, Lois Sauter of Portland, Gregon. Lois was born July 28, 1926,
and they were married on September 7, 1942, and moved to Chicago, where
Lew worked for an insurance company. On November 13, 1948, he was accept-
ed by the Federal Bureau of Investigation under J.Edgar Hoover in Chicago
and then lived in Washington, DC. During World War II, his German back-
ground served him well, and he was assigned to interrogate German prison-
ers in the German language for the FBI. Also, for the FEI in Los Angeles
he interviewed German immigrants for espionage.

Four children were added to this union:

* Michelle, born August 27, 1949, lives in Walnut Creek, Cal. part-
time student. 
** Son: Sasha born. August 6, 1975. In 1092 attends high school, shoe salesman
and model.
* Lynn, born November 13, 1951, lives in Walnut Creek; works for Senior Citizens.
* Joanie Michaelson, born March 16, 1956, lives in Walnut Creek, transcribes medical
records for local hospital, married to Rodney Michaelson. Children:
** Jessica, born September 18, 1975, H.S. student
** Naomi, børn September 22, 1981, elementary student
* Jill, born January 4, 1959, computer whiz, worked for John Hancock Insurance company
until recession in 1991. Going to school part-time and working part-time in Boston.

Lewis was assigned to the Phoenix, Arizona, office, and on April 12, 1950, he was the
senior agent for FBI Los Angeles for 14 years for San Bernardino County. During this time
they lived in Arcadia and San Bernardino. Their last move was in June, 1972, when Lew was
transferred to the San Francisco office, and they made their home across the bay in
Walnut Creek. He worked in the San Francisco until 1978, when President Nixon made it
mandatory for all FBI agents over 55 to retire.

A born story teller, Lew delights his audiences with the harrowing debails of his exciting experiences.
following his forced retirement at such a young age. Lew did various jobs, including
selling solid brass adornments for a hardware company which purchased supplies from Germany.
In 1981 the Federal Government asked Lew to assume various hats while working as an investigative
consultant for the U.S. Air Force and the Department of Defence, a position which he still
assumes to a small extent. From 1988 through 1991 Lew also did work for the nuclear regulary
commission.

At this time, in the spring of 1992, Lew and Lois still live in their Walnut Creek home at at 235
Vallecito Lane. Lois enjoys walking, an exercise which Lew does not indulge in because of a total
hip replacement, but they both enjoy their swimming pool.

