= Branch I: Carl Friedrich Krückeberg (b. 1807) Branch
:page-role: very-wide

[.narrow]
== The Ancestry of Carl Friedrich Krückeberg (b. 1807)

In 1850 the Carl Friedrich Krückeberg family emigrated from Schaumburg-Lippe and settled in Adams county, Indiana.
The document that tells us the town they came from is the xref:derived-church-records:FS-CFK.adoc[]. It tells us
their village was *"Beerenbsuch"* [sic] (more commonly spelled Berenbsuch) in the principality of Schaumburg-Lippe.

TODO: give the Familienschein's document's history and provenance.

It goes on to explain that Carl Friedrich's father, Carl Friedrich Gottlieb, was a shoemaker and his social status was an
*Einlieger*, implying the family lived as tenants--at least at the time of the birth of Carl Friedrich, their 1^st^ 
son and 2^nd^ child.  His mother was from the village of Evensen [sic] (or Evesen) located immediately south of
Berenbusch. Evesen and Berenbusch are also the villages of his baptismal sponsors.

We know from link:https://www.meyersgaz.org/place/10466052[Meyer's Gazetteer] the closest Lutheran Church to Evesen
and Berenbusch was Petzen. Furthermore the bottom of the xref:derived-church-records:FS-CFK.adoc[] mentions the
family's parish and its acting pastor:

[quote]
____ 
Petzen d. 23sten September 1850
Pede vacanti
der vikarirende Prediger

Fürstentum Schaumburg Lippe.

pass:[L. Schwerdtmann von Bergkirchen.]
____

This translates as:

[quote]
____
Petzen, the 23rd of September 1850  
During a pastoral vacancy  
the acting preacher  

Principality of Schaumburg-Lippe  

pass:[L. Schwerdtmann von Bergkirchen.]
(signatory)
____

The acting pastor for Petzen was L. Schwerdtmann of Bergkirchen, and *Petzen* was the parish where the Krückeberg
were members, and it is where their and their ancestor's original birth, baptism, confirmation, marriage and death and
burial records are to be found.

As of November 30, 2025, we only have online access to the Petzen church registers prior to 1827. Those after 1827
are only available at the Lower Saxony State Archive in Bückeburg. Until those have been researched, we
must rely on the xref:derived-church-records:FS-CFK.adoc[] because it states it is derived from the original Petzen
church records: "Laut Angabe des hiesigen Kirchenbuchs..." ("According to the local church register..."). 

While we do have the two Krückeberg biographies who, were founders of Immanuel Lutheran, Decatur, Indiana

. xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[]
. xref:immanuel:ROOT:DEC-BIO-Krueckeberg-02.adoc[]

unlike the xref:derived-church-records:FS-CFK.adoc[] neither mentions the source of their information.  Furthermore
the biography of xref:immanuel:ROOT:DEC-BIO-Krueckeberg-02.adoc[], the first child of Carl Friedrich, gives the
father's name as *"Carl Gottlieb"* not *"Carl Friedrich"*, making it further suspect. 
