= Carl Friedrich Krückeberg (b. 1807) Family Events 
:page-role: very-wide

[.narrow]
== Introduction

In 1850 the Carl Friedrich Krückeberg family emigrated from Schaumburg-Lippe and settled in Adams county, Indiana.
The document that tells us the town they came from is the xref:derived-church-records:FS-CFK.adoc[]. It tells us
their village was *"Beerenbsuch"* [sic] (more commonly spelled Berenbsuch) in the principality of Schaumburg-Lippe.

TODO: give the Familienschein's document's history and provenance.

It goes on to explain that Carl Friedrich's father, Carl Friedrich Gottlieb, was a shoemaker and his social status was an
*Einlieger*, implying the family lived as tenants--at least at the time of the birth of Carl Friedrich, their 1^st^ 
son and 2^nd^ child.  His mother was from the village of Evensen [sic] (or Evesen) located immediately south of
Berenbusch. Evesen and Berenbusch are also the villages of his baptismal sponsors.

The bottom of the xref:derived-church-records:FS-CFK.adoc[] mentions the
family's parish of Petzen and its acting pastor:

[quote]
____ 
Petzen d. 23sten September 1850
Pede vacanti
der vikarirende Prediger

Fürstentum Schaumburg Lippe.

pass:[L. Schwerdtmann von Bergkirchen.]
____

This translates as:

[quote]
____
Petzen, the 23rd of September 1850  
During a pastoral vacancy  
the acting preacher  

Principality of Schaumburg-Lippe  

pass:[L. Schwerdtmann von Bergkirchen.]
(signatory)
____

The acting pastor for Petzen was L. Schwerdtmann of Bergkirchen, and *Petzen* was the parish where the Krückeberg
were members, and it is where their and their ancestor's original birth, baptism, confirmation, marriage and death and
burial records are to be found. link:https://www.meyersgaz.org/place/10466052[Meyer's Gazetteer] also confirms that
the closest Lutheran Church to Evesen and Berenbusch was Petzen.

As of November 30, 2025, we only have online access to the Petzen church registers prior to 1827. Those after 1827
are only available at the Lower Saxony State Archive in Bückeburg. Until those have been researched, we
must rely on the xref:derived-church-records:FS-CFK.adoc[] because it states it is derived from the original Petzen
church records: "Laut Angabe des hiesigen Kirchenbuchs..." ("According to the local church register..."). 

While we do have the two Krückeberg biographies who, were founders of Immanuel Lutheran, Decatur, Indiana

. xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[]
. xref:immanuel:ROOT:DEC-BIO-Krueckeberg-02.adoc[]

unlike the xref:derived-church-records:FS-CFK.adoc[] neither mentions the source of their information.  Furthermore
the biography of xref:immanuel:ROOT:DEC-BIO-Krueckeberg-02.adoc[], the first child of Carl Friedrich, gives the
father's name as *"Carl Gottlieb"* not *"Carl Friedrich"*, making it further suspect. 

== Event Table for Family of Carl Friedrich Krückeberg (1807-185?)

[.narrow]
=== Note on Residence/Village Column

test test test test test test test test test test test test test test test test test test test test test test test test test test test test 

Residence is only truly applicable for Births/Baptisms and Confirmation since infants
and adolescents reside with their family. In the case of marriage, the "residence" of
the bride or groom is their residence at the time of marriage not their future residence,
although the groom's residence often is the future residence. In the case of death/burial,
a residence is not necessarily given but rather "place of death". Therefore, "Residence /
Village" and "No." are populated only for:

. Baptism events
. Confirmation events

For Marriage events:

* Pre-marriage residence(s) of bride and groom are recorded in the Notes column
* Residence / Village and No. columns remain blank

For Death / Burial events:

* Place and time of death and burial are recorded in Notes
* Residence / Village and No. columns remain blank unless the record explicitly states residence

The table is chronologically ordered by Event Date. The following codes are used for each type of
event:

[cols="4,1",options="header",width="30%"]
|===
|Event |Code

|*Birth* |*B* 
|*Baptism* |*Ba*
|*Confirmation* |*C*
|*Marriage* |*M*
|*Death / Burial* |*D*
|===

=== Derived Record Event Table for Carl Friedrich Krückeberg Family

.Derived Record Event Table for Carl Friedrich Krückeberg Family
[cols="1,3,4,4,4,3,1,3,4a,5a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
(Bap./Conf.)
| No.
| Occupation
| Sponsors
| Notes

|B
|21 May 1807
|Carl Friedrich Krückeberg
|Carl Friedrich Gottlieb Krückeberg
|Phlippine Leonore Bleeke *†*
|Evesen
|11
|tailor
|
|2^nd^ child, 1^st^ son

|Bp
|24 May 1807
|Carl Friedrich Krückeberg
|Carl Friedrich Gottlieb Krückeberg
|Phlippine Leonore Bleeke *†*
|Evesen
|11
|tailor
|
. Hans Heinrich Wilharm, +
#11 Evesen 
. Johann Heinrich Deerberg, +
#6 Evensen,
. Jobst Heinrich Krückeberg, +
Beerenbusch.
|

|B
|2 Jan. 1811
|Luise Dorothea Weiland
|Friedrich Wilhelm Weiland
|Anna Katharine Drinckuth
|Evesen
|#20
|
|
|3^rd^ child, 3^rd^ daughter

*Father:* Kolon

|Bp
|2 Jan. 1811
|Luise Dorothea Weiland
|Friedrich Wilhelm Weiland
|Anna Katharine Drinckuth
|Evesen
|#20
|
|
. Dorothea Deerberg, #6 Evesen 
. Katharine Leonore Kuhlmann, #3 Evensen.
|

| M
| 16 Nov 1834
| Carl Friedrich Krückeberg & Luise Dorothea Weiland
| same as birth 
| same as birth
| todo 
| todo 
| todo 
| todo 
| todo 

| B
| 4 Feb 1835
| Carl Heinrich Wilhelm Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
| 
| 
| 
| 
| 

| C
| 15 Apr 1849
| Carl Heinrich Wilhelm Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
|  
|  
| 
| 
| Confirmed on Quasimodogeniti Sunday 

| B
| 15 Oct 1837
| Caroline Philippine Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
|  
|  
| 
| 
| 

| B
| 8 Sep 1840
| Caroline Philippine Sophie Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
|  
|  
| 
| 
| 

| B
| 6 Sep 1843
| Wilhelmine Christine Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
|  
|  
| 
| 
| 

| B
| 23 Jul 1846
| Friederich Wilhelm Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
|  
|  
| 
| 
| 

| B
| 6 Feb 1850
| Ernst Heinrich Krückeberg
| Carl Friedrich Krückeberg
| Luise Dorothea née Weiland
|  
|  
| 
| 
| 
|===

*†* -- The *Bleeken* surname for Phlippine Leonore is in error.

== Original Petzen Records Event Table for the Carl Friedrich Gottlieb Krückeberg Family

[.narrow]
=== Frequency of Krückebergs in the Petzen Records

Reviewing the Petzen records from the early part of the 18th century into the early part of the 19th century, we find that
there are not many Krückeberg records because there were not that many Krückeberg families in the Petzen parish.
This greatly aids finding the prior generation to Johann Heinrich and Carl Friedrich Krückeberg. However, it
doesn't eliminate the requirement of examining every page of the church register, which is unindexed.

We can immediately look for those Krückebergs that lived at the same address, had the same parents, whose father
has the same occupation and the same status (Stand in German), had the network of sponsors, etc.
We can use the same technique to find the prior generation.

Especially helpful in confirming the individual in different records is the Nachträge (addenda) that is sometime
occurance in the margins of a record that references past of future church ceremonies involving a individual
and sometimes their parents. So in addition to the event table, we also have a separate xref:#nachtraege[Nachträge
table].

*TODO:* Move this statement where it better fits:
Carl Friedrich Gottlieb Krückeberg was the father of Carl Friedrich Krückeberg born in 1807.

[[event-table-petzen-cfg-krueckeberg-family]]
=== Event Table

.Petzen Parish Records Event Table for Carl Friedrich Krückeberg Family
[cols="1,2,3,3,3,2,1,2,3a,4a,3a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| No.
| Occupation
| Sponsors
| Notes
| Record Page(s)

| Birth
| 7 Dec. 1803
| Christine Philippine Krückeberg
| Carl Friedrich Krückeberg
| Philippine Werkmeister
| Evesen
| 
| 
| 
| Father: Einlieger 
| xref:petzen:PET-B-1803c.adoc[]

| Baptism
| 11 Dec. 1803
| Christine Philippine Krückeberg
| Carl Friedrich Krückeberg
| Philippine Werkmeister
| Evesen
| 
| 
|
Mrs. Kruckeberg and +
Weyland from Berenbusch 
| Father: Einlieger 
| xref:petzen:PET-B-1803c.adoc[]

| Birth
| 21 May 1807
| Carl Friedrich Krückeberg
| Carl Friedrich Gottlieb Krückeberg
| Philippine Lenore née Bleeken *†* +
from # 11 Evesen
| Berenbusch
| 14
| tailor
| Father's status: Einlieger
|
1^st^ son, 2^nd^ child

Father is *Einlieger* 

Mother from # 11 Evesen
|xref:petzen:PET-B-1807a.adoc[]

| Baptism 
| 24 May 1807
| Carl Friedrich Krückeberg 
| Carl Friedrich Gottlieb Krückeberg
| Philippine Lenore née Bleeken *†* +
from # 11 Evesen
| Berenbusch 
| 14
| tailor
|
. Hans Heinrich Wilharm, n. 11 Evesen
. Johann Heinrich Deerberg, n. [6] Evesen
. Jobst Heinrich Krückeberg, Bärenbusch
|
Father is *Einlieger* 

Mother from # 11 Evesen
|xref:petzen:PET-B-1807a.adoc[]

|Birth
|2 Dec. 1812
|Caroline Dorothee Krückeberg
|Carl Friedrich Gottlieb Krückeberg
|Philippine Leonore  née Bleeken *†* +
from n. 11 Evesen
|Berenbusch
|18
|
|3^rd^ child, 2^nd^ daughter
|xref:#nachtraege[Nachträge exists for her and her father]
|xref:petzen:PET-B-1812a.adoc[]

|Baptism
|6 Dec. 1812
|Caroline Dorothee Krückeberg
|Carl Friedrich Gottlieb Krückeberg
|Philippine Leonore née Bleeken *†* +
from n. 11 Evesen
|Berenbusch
|18
|
|
. Marie Dorothee Deerberg, n. 6 Evesen
. Caroline Charolitte Sieckmeier, n. 4 in Evesen.
|xref:#nachtraege[Nachträge exists for her and her father]
|xref:petzen:PET-B-1812a.adoc[]

| Confirmation
| 6 April 1817
| Christine Philippine Krückeberg
|
|
| Berenbusch
| 18
|
|
|Confirmed: Quasimodogeniti Sunday, 1817 
|xref:petzen:PET-C-1817a.adoc[]

| Confirmation
| 8 April 1821
| Carl Friedrich Krückeberg 
| 
| 
| Berenbusch
| 14
|
|
|Confirmed: Quasimodogeniti Sunday, 1821 
|xref:petzen:PET-C-1821a.adoc[]
|===

*†* -- The *Bleeken* surname for Phlippine Leonore is in error.

[.narrow]
=== Comments

The event table shows that for each of the three children born to Carl Friedrich Gottlieb Krückeberg and Philippine
Leonore Werkmeister (or to Philippine Leonore Bleeke as her name is recorded baptism records of her 2nd and 3rd
children, a contradication that will be explained later), we find:

*  village of Berenbush is the same.
*  the father's status as Einlieger is the same in the first two baptism records
*  the father’s occupation oftailor is the same in the 2^nd^ and #^rd^ baptism records.

Since the baptism records for Carl Friedrich and Caroline Dorothee Krückeberg give their birth order and their
birth order among the sons or daughters, we know that between 1803, when their first child was born, and 1812,
whhen their was 1812, no other children were born. While I have examined every single Petzen birth-baptism record
between 1803 and 1813, this birth-order fact provides a double check that guarantees no other births to this couple
were inadvertently overlooked. Furthermoe, since all baptism records after 1812 were carefully examined and no
further births to this couples were found recorded, we have the entire family.

[.narrow]
[[nachtraege]]
== Nachträge Table

*TODO* Add the information above and the information in this paragraph below
into a conclusions section below.

The baptism record for Caroline Dorothee Krückeberg contains Nachträge, mariginal addenda, that lists
her future marriage and burial and death dates as well as her father's exact baptism date. Having her 
father's baptism dates allows us to immediately locate his birth record and determine who his parents are,
where they lived--not to mention other details his baptism record might have. It provides the connecting
link to the prior generation, the proof of who his parent's are.

.Nachträge table for xref:#event-table-petzen-cfg-krueckeberg-family[]
[cols="3,3,2,4a,3a",options="header"]
|===
| Name of Subject
| Source Record
| Referenced Ceremony
| Nachtrag Text

| Caroline Dorothee Krückeberg
| xref:petzen:PET-B-1812a.adoc[]
| xref:#event-table-petzen-cfg-krueckeberg-family[Marriage]
| „cop. 25.10.35“ +
married 15 Oct. 1835

| Caroline Dorothee Krückeberg
| xref:petzen:PET-B-1812a.adoc[]
| xref:#event-table-petzen-cfg-krueckeberg-family[Death]
| „gest.14.12.69“ +
died 14 Dec. 1869

| Carl Friedrich Gottlieb Krückeberg
| xref:petzen:PET-B-1779b.adoc[]
| xref:#event-table-petzen-cfg-krueckeberg-family[Baptism]
| „get. 18.4.1779“ +
baptized 18 Mar. 1779

| Carl Friedrich Gottlieb Krückeberg
| xref:petzen:PET-B-1779b.adoc[]
| xref:#event-table-petzen-cfg-krueckeberg-family[Marriage]
| „cop. 13.3.03“ +
(married 13 Mar. 1803)
|===

[.narrow]
== Notes on Event Interpretation

* Explain abbreviations (e.g., hÿ, eod., do.)
* Note variant spellings
* Note ditto marks or marginalia
* Note uncertain readings
* Note conflicting entries
* Note cases requiring lookup in original scans

[.narrow]
== Source and Citation Information

* Full citation to source (BCG-style)
* Provenance notes if derivative
* Link or xref to image/document page
* Repository or archive reference
* Access date (if online database)

[.narrow]
== Analytical Observations (optional)

* Identity hypotheses
* Cluster groupings (family units)
* Sponsor network implications
* Residence movement
* Relationship to emigrants

