= The Ancestry of the Krückebergs of Union Township, Adams County, Indiana

In 1849 the family of Johann Heinrich Krückeberg emigrated from the village of Berenbusch, Schaumburg-Lippe,
and settled in Union township, Adams County, Indiana. The following year the family of Carl Friedrich Krückeberg
also left Berenbusch and joined them.

The trail of documentary evidence that reveals Berenbusch as the place of origin of these two Krückeberg families
leads backs to two documents:

* the xref:derived-church-records:FS-CFK.adoc[family certificate of the immigrant Carl Friedrich
Krückeberg]footnote:[Family certificate of the emigrant Carl Friedrich Krückeberg (Schaumburg-Lippe), typewritten copy;
provenance unknown. Internal evidence shows Petzen parish certification by the acting pastor L. Schwerdtmann from Bergkirchen. My late father’s first cousin Melvin Krueckeberg supplied me a copy; he had received it from
his (and my late father’s) first cousin, Harry Frederick Krueckeberg, who believes his late father prepared the typescript (per email).], and
* the Immanuel Lutheran, Decatur Indiana, founder's xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[biography of Johann Heinrich Krückeberg]footnote:[Immanuel
Lutheran Church (Decatur, Indiana), church register, 1850–1905, biographical entry for Johann Heinrich
Krückeberg. The register was obtained on DVD directly from the church.]

The provenance of the first document is given in its opening sentence: "Laut Angabe des hiesigen Kirchenbuchs..." (according to the local
church register). The parish village of *Petzen* is identified at the bottom of the document: 

[quote, translation of the 'family record of the emigrant Carl Friedrich Krückeberg']
____
Die Übereinstimmung vorstehender Angaben mit den hiesigen
Kirchenbüchern bescheinigt den Auswanderern unter Anwuenschung
des göttlichen Segens — sub fide pastorali

*Petzen* d. 23sten September 1850
Pede vacanti
der vikarirende Prediger

Fürstentum Schaumburg Lippe.

{empty}L. Schwerdtmann von Bergkirchen.

*English translation:*  

The foregoing statements are hereby certified as conforming to the local church registers and are issued to the
emigrants with best wishes for God’s blessing, under pastoral authority.  

*Petzen*, 23 September 1850.  
The parish being vacant,  
the acting pastor.  

Principality of Schaumburg-Lippe.  

{empty}L. Schwerdtmann of Bergkirchen.
____

While the provenance of the biography is not given, both documents are strictly religous profiles composed soley from the
contents of the Petzen church register records involving the family members. They serve as an unofficial index of the Petzen
parish records they reference. This is extremely helpful because the Petzen parish registers contain neither an index nor a
table of contents. 
