= Krückeberg Ancestry

The trail of documentary evidence that reveals the place of origin of the two Krückeberg families who settled
in Adams County, Indiana, in 1849 and 1850, leads backs to two documents:

* the xref:derived-church-records:FS-CFK.adoc[family certificate of the immigrant Carl Friedrich
Krückeberg]footnote:[Family certificate of the emigrant Carl Friedrich Krückeberg (Schaumburg-Lippe), typewritten copy;
provenance unknown. Internal evidence shows Petzen parish certification by the acting pastor L. Schwerdtmann from Bergkirchen. My late father’s first cousin Melvin Krueckeberg supplied me a copy; he had received it from
his (and my late father’s) first cousin, and he believes his late father prepared the typescript (per email).], and
* the Immanuel Lutheran, Decatur Indiana, founder's xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[biography of Johann Heinrich Krückeberg]footnote:[Immanuel
Lutheran Church (Decatur, Indiana), church register, 1850–1905, biographical entry for Johann Heinrich
Krückeberg. The register was obtained on DVD directly from the church.]


The trail of documentary evidence that reveals the place of origin of the two Krückeberg families who settled
in Adams County, Indiana, in 1849 and 1850, leads backs to two documents:

* the xref:derived-church-records:FS-CFK.adoc[family certificate of the immigrant Carl Friedrich Krückeberg]footnote:[Family certificate of Carl Friedrich Krückeberg (Schaumburg-Lippe), typewritten copy; provenance unknown. Internal evidence shows Petzen parish certification by the acting pastor (name and credentials at foot of document). My late father’s first cousin Melvin Krueckeberg supplied me a copy; he had received it from his (and my late father’s) first cousin, and he believes his late father prepared the typescript (per email).]

* the biography of Johann Heinrich Krückeberg in the Immanuel Lutheran Church, Decatur, Indianafootnote:[Immanuel
  Lutheran Church (Decatur, Indiana), church register, 1850–1905, biographical entry for Johann Heinrich
Krückeberg. The register was obtained on DVD directly from the church.]



