= The Ancestry of the Krückebergs of Union Township, Adams County, Indiana

In 1849 the family of Johann Heinrich Krückeberg emigrated from the village of Berenbusch, Schaumburg-Lippe,
and settled in Union township, Adams County, Indiana, and the following year, the family of Carl Friedrich Krückeberg likewise
emigrated from Berenbusch and joined them in Union township.

The trail of documentary evidence that reveals the village of Berenbusch as the place of origin of these two Krückeberg families
leads backs to two documents:

* the xref:derived-church-records:FS-CFK.adoc[family certificate of the immigrant Carl Friedrich
Krückeberg]footnote:[Family certificate of the emigrant Carl Friedrich Krückeberg (Schaumburg-Lippe), typewritten copy;
provenance unknown. Internal evidence shows Petzen parish certification by the acting pastor L. Schwerdtmann from Bergkirchen. My late father’s first cousin Melvin Krueckeberg supplied me a copy; he had received it from
his (and my late father’s) first cousin, Harry Frederick Krueckeberg, who believes his late father prepared the typescript (per email).], and
* the Immanuel Lutheran, Decatur Indiana, founder's xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[biography of Johann Heinrich Krückeberg]footnote:[Immanuel
Lutheran Church (Decatur, Indiana), church register, 1850–1905, biographical entry for Johann Heinrich
Krückeberg. The register was obtained on DVD directly from the church.]

The first document's provenance is given in its first sentence: "Laut Angabe des hiesigen Kirchenbuchs..." (according to the local
church register). The parish's name was Petzen, which appears this block of text at the bottom of the document: 

[quote, translation of the _family record of the emigrant Carl Friedrich Krückeberg_]
____
Petzen d. 23sten September 1850
Pede vacanti
der vikarirende Prediger

Fürstentum Schaumburg Lippe.

L. Schwerdtmann von Bergkirchen.
____
