= Johann Heinrich Krückeberg (1744-1822) Event Table
:page-role: very-wide
:sectnums!:

== Introduction

On 21 March 1822, a Johann Heinrich Krückeberg died who was a Leibzüchter, a retired farmer who:

* has handed the farm over to his heir,

* but still has a lifetime right to housing, support, and use of part of the property.

His age is given as 78 years, 2 months and 3 weeks. Subtracting this precise age from 21 March 1822
places his birth on 31 December 1743. But no birth for a Johann Heinrich Krückeberg was recorded on
this date; however, a Johann Heinrich Krückeberg was born on 19 January 1744, which is 
78 years, 2 months and 3 days.... 



died a "78 years, 3 months and 3 weeks." This would place his birth on 19 January
1744 which is the precise date the precise birthday of the Johann Heinrich cracker Barrel born in 1744
*Under Development*
// See: https://chatgpt.com/share/691fa228-7674-8004-91a5-1bf305719fb1/

[cols="1,1,2,2,2,2,1,1,2,3,2",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| House Number
| Occupation
| Sponsors / Witnesses
| Notes
| Record Page

| Marriage
| 14  June 1761
| Johann Heinrich Krückeberg &
Anne Chritine Elisabeth Seeger
| not given
| not given
|Groom: Berenbusch +
Bride: Evesen
| not given
| 
| 
|If the groom is the Johann Heinrich Krückeberg born in 1744, he would be only 17
at the time of marrage, while his bride would have been 25.
| xref:petzen:PET-M-1761a.adoc[]
|===
