= Johann Heinrich Krückeberg (1744-1822) Event Table
:page-role: very-wide
:sectnums!:

[.narrow]
== Introduction

On 21 March 1822, a Johann Heinrich Krückeberg died who was a Leibzüchter, a retired farmer who:

* has handed the farm over to his heir,

* but still has a lifetime right to housing, support, and use of part of the property.

His age is given as 78 years, 2 months and 3 weeks. Subtracting this precise age from 21 March 1822
places his birth on 31 December 1743, a date on which no births occurred in the Petzen parish.
However, on 19 January 1744, a Johann Heinrich Krückeberg was born, which is 78 years, 2 months and
3 days (not 3 weeks) from 21 March 1822. Did the scribe accidently write "weeks" instead of "days"?
Can we in any other way further establish that the Johann Heinrich Krückeberg who was born 19 January
1744 is the same Johann Heinrich Krückeberg who died on 21 March 1822?

[.narrow]
== Facts

* His age of 78 years, 2 months and 3 weeks (maybe 3 days).
* He was a Leibzüchter and his heir is revealed indirectly in the records of his children.
* The Johann Heinrich Krückeberg who married Ilse Anna Marie Elisabeth Schäkeln Schakele 7 Nov. 1773
was a 1.) widower and 2.) from Berenbusch.
* Is the first born son named after the paternal grandfather?
* The Johann Heinrich Krückeberg who married Philippine Dorothea Beucken on 11 April 1802
was a 1.) widower 2.) Leibzüchter and 3.) lived a #10 Berenbusch.
  
=== The Leibzüchter Fact

Let's begin with the "Leibzüchter" fact.  We will use the table below that when filled out should reveal:

1. His son **Jobst Heinrich remained all his adult life at No. 10 Berenbusch**
2. His son **Johann Heinrich relocated permanently to No. 19 Evesen through marriage**
3. **The father died at the ancestral Hof (No. 10)**
4. **Jobst Heinrich died at the same Hof**, confirming succession
5. Their children were raised on **two separate household lines**

This is provide proof that **Jobst Heinrich was the inheriting son**
* **Johann Heinrich founded a cadet branch in Evesen**

*Questions:* 
. Could the Johann Heinrich Krückeberg who married in 1761 be the Johann Heinrich Krückeberg
who also married in 1727? 
+
Answer: No because he apparently was dead: xref:petzen:PET-D-1759a.adoc[].

== Event Table

.Events based on Petzen Church Records
[cols="1,2,3,3,3,2,1,2,3a,4a,3a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| House Number
| Occupation
| Sponsors
| Notes
| Record Page

| Baptism
| 24 Mar. 1765
| Jobst Heinrich Krückeberg
| Johann Heinrich Krückeberg 
| 
| Berenbusch
| 
| 
| 
|
. Rösener, from Evesen im kurzen Bruche
|xref:petzen:PET-B-1767a.adoc[]

| Baptism
| 5 Jul. 1767
| Johann Heinrich Wilhelm Krückeberg 
| Johann Heinrich Krückeberg
| Anne Christine Elisabeth née Seeger
| Berenbusch
|
| 
|
. Jobst Wilhelm Weiland, Berenbusch
|
|xref:petzen:PET-B-1767a.adoc[]

|Burial
|23 June 1771
|stillborn son
|Johann Heinrich Krückeberg
|
|Berenbusch
|
|
|
|
|xref:petzen:PET-D-1771a.adoc[]

|Burial
|27 Aug. 1773
|stillborn son
|Johann Heinrich Krückeberg
|
|Berenbusch
|no. 10
|
|
|No. 10 appears for the first time
|xref:petzen:PET-D-1771a.adoc[]

|Burial
|29 Aug 1773
|Anna Christina  Seeger
|Johann Heinrich Krückeberg
|Berenbusch
|
|
|
|
|
died from childbirth complication

*age:* 36 years old
|xref:petzen:PET-D-1773b.adoc[]

|Marriage
|7 Nov. 1773
|Johann Heinrich Krückeberg
|Ilse Anna Maria Elisebeth 
|
|
|
|
|
|groom is widower née Schakel
|
|===

== Other Clues

