= Johann Heinrich Krückeberg (1744-1822) Event Table
:page-role: very-wide
:sectnums!:

[.narrow]
== Introduction

On 21 March 1822, a Johann Heinrich Krückeberg died who was a Leibzüchter, a retired farmer who:

* has handed the farm over to his heir,

* but still has a lifetime right to housing, support, and use of part of the property.

His age is given as 78 years, 2 months and 3 weeks. Subtracting this precise age from 21 March 1822
places his birth on 31 December 1743, a date on which no births occurred in the Petzen parish.
However, on 19 January 1744, a Johann Heinrich Krückeberg was born, which is 78 years, 2 months and
3 days (not 3 weeks) from 21 March 1822. Did the scribe accidently write "weeks" instead of "days"?
Can we in any other way further establish that the Johann Heinrich Krückeberg who was born 19 January
1744 is the same Johann Heinrich Krückeberg who died on 21 March 1822?

Further points about Johann Heinrich are, on xref:petzen:PET-M-1773a.adoc[7 November 1773 the widower Johann Heinrich Krückeberg
from Berenbusch marries marries Ilse Anna Marie Elisabeth née Schakel]. The odds of there being two
Johann Heinrich Krückebergs from Berenbusch who are both widowers is negligible.

[.narrow]
== Facts

* He dies at age of 78 years, 2 months and 3 weeks (maybe 3 days).
* He is mentioned as a Leibzüchter when he xref:petzen:PET-M-1802b.adoc[marries on 11 April 1802] and when he
xref:petzen:PET-D-1822a.adoc[dies on 21 March 1822]. For both events, his address is #10 Berenbusch.
However, when his wife is xref:petzen:PET-D-1819a.adoc[buried on 6 January 1819] "he" is described as  

[quote]
____
vormaligen Hofmeisters auf dem Reinen-Neelhof Johann Heinrich Krückeberg, Einlieger beÿ n.13 in Bärenbusch
____

The addresses are different. We know that #13 Berenbusch was where the husband of Johann Heinrich's 
daughter Maria Philippine Krückeberg. Friedrich Wilhelm Raulfing, lived, as their xref:petzen:PET-M-1812a.adoc[wedding 
ceremony on 10 May 1812] shows. It is the "Place" where his wife, Philippine Dorothea nee Beucke died. This was
the "most recent residence of the deceased". So if Johann Heinrich was staying there, too, at #13 Berenbusch. 
Maybe that is why he is called an "Einlieger bei (at) #13 Berenbusch". He was a "tenant" there temporarily? 
* The Johann Heinrich Krückeberg who married Ilse Anna Marie Elisabeth Schäkeln Schakele 7 Nov. 1773
was a
. widower and 
. from Berenbusch.
* Is the first born son named after the paternal grandfather? Is this naming pattern (of the first
paternal grandson being named after his patern grandfather) evident?
* The Johann Heinrich Krückeberg who married Philippine Dorothea Beucken on 11 April 1802
was a
. widower
. Leibzüchter
. lived a #10 Berenbusch.
* But when Philippine Dorothee née Beucke Krückeberg dies, her burial record states her husband, Johann
Heinrich Krückeberg is an *Einlieger beÿ n.13 in Bärenbusch*. Most of the records involving Johann
Heinrich refer to *# 10 Berenbusch* not *# 13 Berenbusch*.
+
*NOTE*: The Bückeburg archive has: Stätte # 13 Berenbusch.
* At his death in 1822, he is only survived by two sons. Yet the Johann Heinrich Krückeberg, who married
Ilse Anna Marie Elisabeth Schekel, had apparently three children. 
  
=== The Leibzüchter Fact

Let's begin with the "Leibzüchter" fact.  We will use the table below that when filled out should reveal:

1. His son **Jobst Heinrich remained all his adult life at No. 10 Berenbusch**
2. His son **Johann Heinrich relocated permanently to No. 19 Evesen through marriage**
3. **The father died at the ancestral Hof (No. 10)**
4. **Jobst Heinrich died at the same Hof**, confirming succession
5. Their children were raised on **two separate household lines**

This is provide proof that **Jobst Heinrich was the inheriting son**
* **Johann Heinrich founded a cadet branch in Evesen**

*Questions:* 
. Could the Johann Heinrich Krückeberg who married in 1761 be the Johann Heinrich Krückeberg
who also married in 1727? 

*Answer:* No because he apparently was dead: xref:petzen:PET-D-1759a.adoc[].

== To Find

=== Baptism/Birth Records

After 1782 for Johann Heinrich Krückeberg and Anna Marie Schakel. Start here: https://www.archion.de/p/4f686bb923/

Reviewed: Thru 1784  = All of 1641-1784 volume.

.Baptisms Reviews
[width="75%"]
|===
|Volume|Progress|New Records Found

|Verzeichnis der Getauften und Konfirmierten 1641-1784|Reviewed all|None

|Verzeichnis der Getauften, Konfirmierten, Getrauten und Gestorbenen 1785-1827|Start at image 31 to start|
|===

=== Burial/Death Records

Find the burial/death record of Anna Maria Elisabeth nee Schäkel/Schekel/Schakel Krückeberg. 

.Deaths/Burials Reviews
[width="75%"]
|===
|Volume|Progress|New Records Found

|Verzeichnis der Getauften und Konfirmierten 1641-1784|Reviewed all|None

|Verzeichnis der Getauften, Konfirmierten, Getrauten und Gestorbenen 1785-1827|yet to start|
|===


. All of " Verzeichnis der Getrauten und Gestorbenen 1641-1784".
. Resume image 221 from "Verzeichnis der Getauften, Konfirmierten, Getrauten und Gestorbenen 1785-1827".

== Event Table

.Events based on Petzen Church Records
[cols="1,2,3,3,3,2,1,2,3a,4a,3a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| House Number
| Occupation
| Sponsors
| Notes
| Record Page

|Marriage
|14 June 1761
|Johann Heinrich Krückeberg & Anne Christine Elisabet Seeger
|not given
|not given
2+|
*groom:* Berenbusch

*bride:* Evesen
|
|
|
|xref:petzen:PET-M-1761a.adoc[]

| Baptism
| 24 Mar. 1765
| Jobst Heinrich Krückeberg
| Johann Heinrich Krückeberg 
| 
| Berenbusch
| 
| 
| 
. Rösener, from Evesen im kurzen Bruche
|
|xref:petzen:PET-B-1765a.adoc[]

| Baptism
| 5 Jul. 1767
| Johann Heinrich Wilhelm Krückeberg 
| Johann Heinrich Krückeberg
| Anne Christine Elisabeth née Seeger
| Berenbusch
|
| 
|
. Jobst Wilhelm Weiland, Berenbusch
|
|xref:petzen:PET-B-1767a.adoc[]

|Burial
|23 June 1771
|stillborn son
|Johann Heinrich Krückeberg
|
|Berenbusch
|
|
|
|
|xref:petzen:PET-D-1771a.adoc[]

|Burial
|27 Aug. 1773
|stillborn son
|Johann Heinrich Krückeberg
|
|Berenbusch
|# 10
|
|
|No. 10 appears for the first time
|xref:petzen:PET-D-1773a.adoc[]

|Burial
|29 Aug 1773
|Anna Christina Seeger
| 
|Berenbusch
|
|
|
|
|
died from childbirth complication

died at #10 Berenbusch

wife of Johann Heinrich Krückeberg

*age:* 36 years old
|xref:petzen:PET-D-1773b.adoc[]

|Marriage
|7 Nov. 1773
|Johann Heinrich Krückeberg & Ilse Anna Maria Elisebeth Schakel
|
|
|
|
|
|
|
*groom:* from Berenbusch

*bride:* from Päpinghausen, whose parish is Frille
|xref:petzen:PET-M-1773a.adoc[]

|Baptism
|10 Sep. 1775
|Anna Christina Maria Krückeberg
|Johann Heinrich Krückeberg
|Anna Maria Elisabeth Schekel
|Berenbusch
|
|
|
. the young Mostin from Berenbusch
|
|xref:petzen:PET-B-1775b.adoc[]

|Baptism
|18 Apr. 1779
|Carl Friedrich Gottlieb
|Johann Heinrich Krückeberg
|Anna Maria née Schekel
|Berenbusch
|
|
|
. Otto Rösener, estate administrator +
on the Höckersau (Höcker's estate).
|
|xref:petzen:PET-B-1779b.adoc[]

|Baptism
|13 Jan. 1782
|Johann Sophie Charlotte Krückeberg
|Johann Heinrich Krückeberg
|Anna Maria Elisabeth Schäkel
|
|
|
|
. Johanna Sophie Margdelena Wilkening, Hockers Aue
. Sophie Charlotte Rösener, Petzen
|
|xref:petzen:PET-B-1782a.adoc[]

|Marriage
|11 Apr. 1802
|Johann Heinrich Krückeberg & Philippine Dorothea Beucke
|not given
|not given
2+|
*groom:* #10 Berenbusch

*bride:* Meinsen
|Leibzüchter
|
|*groom:* widower

*bride:* Einliegerin

*bride's age:* approximately 38 (based on age at death)

*Comment under bride's name:* [?] by him several years ago
|xref:petzen:PET-M-1802b.adoc[]

|Death
|6 Jan. 1819
|Philippine Dorothee nee Beucke Krückeberg
|not given
|not given
|Berenbusch
|#13
|Einlieger
|
|
*Age:* 54

*Cause of Death:* penumonia/consumption

*Husband's Status:* Einlieger at # 13 Bärenbusch.

*Husband’s former Occupation:* Hofmeisters auf dem Reinen-
Neelhof

*Survivors:* Husband and a daughter

The decedent was not baptized in Petzen. There is no Beucke
baptism between 1764-1765 in the Petzen Kirchenbuch.
|xref:petzen:PET-D-1819a.adoc[]

|Death
|21 Mar. 1822
|Johann Heinrich Krückeberg
|not given
|not given
|Bärenbusch
|#10
|
|
|
*Cause of death:* debility of old age

*Status:* Leibzüchter at #10 Bärenbusch

*Age:* 78 years. 2 months, 3 weeks

*Survivors:* 2 sons

*Question:* Why not survived by and daughters?
|xref:petzen:PET-D-1822a.adoc[]
|===

== Nachträge

//|===


//|===
