= Jobst Heinrich Krückeberg (1779-1822) Family Event Table
:page-role: very-wide
:sectnums!:

[.narrow]
== Introduction

Using the Immanuel Lutheran biography of xref:jhk-1806-events.adoc#event-table[Johann Heinrich Krückeberg] as a
guide to the Petzen church records takes us to his Petzen xref:petzen:PET-B-1806a.adoc[1807 birth record],
which confirms his birth date, his parents names (which are further clarified), his baptismal sponsors, and the
family's residence. It alstakes us to his Petzen 1820 confirmation record. Then using these details--the parent's
names, their residence, the father's occupation, and any family attributes--as a guide, we can look for other
children born to this couple.

In one of the birth records of one of the children the mother's surname is spelled differently, but she is clearly
the same person because their given names are the same as is her place of origin and the spelling is not
so different that it greatly differs in pronunciation.

== Contradictions and Questions

Jobst Heinrich Krückeberg clearly appears to have had five daughters and one son, five total children. Yet when 
Johann Heinrich is born in 1806, he is, according to his birth-baptism record, the *4^th^ child and 1^st^ son
of the first marriage*. But he had only one marraige--didn't he--and he had five daughters before his first and
only son was born--correct?

When Jobst Heinrich dies in 1822, he death record recrds the survivors as *"a widow and four children, namely three
daughters and one son."* This could be true, if two of the five daughters had died before him. If two
of hise daughters married spouses from other parishes, where they would have married, and subsequently died, then
only three daughters would have survived him. But this is something we will never know, since we
have no way of knowing, if they did marry someone outside the Petzen congregation, who they married and which parish
recorded the subsequent death. So we need to locate all the marriage records of the daughter.

== Petzen Original Records Event Table for Jobst Heinrich Krückeberg Family

*Question:* In the birth record of the first child, Philippine Caroline Christine, her Krückeberg grandmother is a baptismal
sponsor. She is still alive! Who would this be?

.Events based on xref:??
[cols="1,2,3,3,3,2,1,2,3a,4a,3a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| House Number
| Occupation
| Sponsors
| Notes
| Record Page

|Birth
|4 Aug. 1806
|Johann Heinrich Krückeberg
|Jobst Heinrich Krückeberg
|Christine Philippine Leonore Tegtmeier, from Evesen
|Bärenbusch
|10
|Schuster Amtsmeister (Shoemaker Guild Master)
|4^th^ child, 1^st^ son
|
|xref:petzen:PET-B-1806a.adoc[]

|Baptism
|17 Aug. 1806
|Johann Heinrich Krückeberg
|Jobst Heinrich Krückeberg
|Christine Philippine Leonore Tegtmeier, from Evesen
|Bärenbusch
|10
|Schuster Amtsmeister (Shoemaker Guild Master)
|
. Carl Friedrich Gottlieb Krückeberg, Einlieger in Bärenbush
. C Friedrich Tegtmeier from Meinsen
|
|xref:petzen:PET-B-1806a.adoc[]

|Confirmation
|2 April 1820
|Johann Heinrich Krückeberg
|not given
|not given
|Bärenbusch
|not given
|not given
|
|Quasimodigeniti win 1818 was 2 Apr. 1818
|xref:petzen:PET-C-1820a.adoc[]
|===
