= Jobst Heinrich Krückeberg (1779-1822) Family Event Table
:page-role: very-wide
:sectnums!:

[.narrow]
== Introduction

Using the event table for Johann Heinrich Krückeberg (1806-1879) 

This information togeter with all and any information found in the Petzen church records of prospective family
members will guide our research strategy in building his family of origin.

== Steps

The xref:jhk-1806-events.adoc#event-table[] takes us to his Petzen xref:petzen:PET-B-1806a.adoc[1807 birth record],
which confirms his birth date, his parents names, which are further clarified, his baptismal sponsors, and the
village where the family lived. The xref:jhk-1806-events.adoc#event-table[] also takes us to his Petzen 1820
confirmation record. Using the parent's names, their residence, the father's occupation, and any family attributes
as a guide, we looks for other children born to this couple and their confirmation and marriage records.

Answer: 
* The record states he was the  the 4^th^ child and 1`^st^ son of the *1^st^ marragie*.
* When Jobst Heinrich, his father, died, he was survied by "his widow 4 children, namely 3 daughters and 1 son".

== Contradictions and Questions

Jobst Heinrich Krückeberg clearly appears to have had five daughters and one son, five total children. Yet when 
Johann Heinrich is born in 1806, he is, according to his birth-baptism record, the *4^th^ child and 1^st^ son
of the first marriage*. But there was only one marraige--right?

When Jobst Heinrich dies in 1822, this curious "fact" is repeated. He is survived by "a widow and ffour children,
namely three daughters and one son." It could be that two of the five daughter died, which left three daughters.
If  two of the daughters married spouses from other parishes, and subsequently died--something we will never know,
then only three daughters would have survived him.

In one of the birth records of one of the children the mother's surname is spelled differently, but she is clearly
the same person because their given names are the same as is her place of origin and the spelling is not
so different that it greatly differs in pronunciation.

In the birth record of the first child, Philippine Caroline Christine, her Krückeberg grandmother is a baptismal
sponsor. She is still alive! Who would this be?

== Petzen Original Records Event Table for Jobst Heinrich Krückeberg Family

.Events based on xref:??
[cols="1,2,3,3,3,2,1,2,3a,4a,3a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| House Number
| Occupation
| Sponsors
| Notes
| Record Page

|Birth
|4 Aug. 1806
|Johann Heinrich Krückeberg
|Jobst Heinrich Krückeberg
|Christine Philippine Leonore Tegtmeier, from Evesen
|Bärenbusch
|10
|Schuster Amtsmeister (Shoemaker Guild Master)
|4^th^ child, 1^st^ son
|
|xref:petzen:PET-B-1806a.adoc[]

|Baptism
|17 Aug. 1806
|Johann Heinrich Krückeberg
|Jobst Heinrich Krückeberg
|Christine Philippine Leonore Tegtmeier, from Evesen
|Bärenbusch
|10
|Schuster Amtsmeister (Shoemaker Guild Master)
|
. Carl Friedrich Gottlieb Krückeberg, Einlieger in Bärenbush
. C Friedrich Tegtmeier from Meinsen
|
|xref:petzen:PET-B-1806a.adoc[]

|Confirmation
|2 April 1820
|Johann Heinrich Krückeberg
|not given
|not given
|Bärenbusch
|not given
|not given
|
|Quasimodigeniti win 1818 was 2 Apr. 1818
|xref:petzen:PET-C-1820a.adoc[]
|===
