= Jobst Heinrich Krückeberg (1779-1822) Family Event Table
:page-role: very-wide
:sectnums!:

[.narrow]
== Introduction

Using the event table for Johann Heinrich Krückeberg (1806-1879) as

In addition to the information in his immanuel biograhy, we also have the Rentcammer (Fiscal Chamber of the
Schaumburg-Lippe government) case files found in the state archive to help us to discover Johann Heinrich 
Krückeberg's family of origin. There are three case files that mentioned Johann Heinrich and his father Jobst
Heinrich, one also mentions his mother. These are a backup source we can turn to if needed.

This information togeter with all and any information found in the Petzen church records of prospective family
members will guide our research strategy in building his family of origin.

== Steps

The xref:jhk-1806-events.adoc#event-table[] takes us to his Petzen xref:petzen:PET-B-1806a.adoc[1807 birth record],
which confirms his birth date, his parents names (which are further clarified), his baptismal sponsors, and the
village where the family lived. The  xref:jhk-1806-events.adoc#event-table[] also takes us to his Petzen 1820
confirmation record. 

Using the parent's names, their residence, and the father's occupation, we next look for other children born to this
couple, and we find four older daughters?

QUESTION: Jhk's birth record states he is the 4^th^ child and 1`^st^ son. How could he then have four older
sisters?

Answer: 
* The record states he was the  the 4^th^ child and 1`^st^ son of the *1^st^ marragie*.
* When Jobst Heinrich, his father, died, he was survied by "his widow 4 children, namely 3 daughters and 1 son".

== Contradictions

Jobst Heinrivh Krückeberg clearly appears to have had five daughters and one son, five total children, because
each of the children has:

create a table?

* the same parents,
* and the same Village,
* and I believe the same numeric address

Does each of the children also has a confirmation record? That would be two records for each child.
 
There isn't really a good explanation why the record of the birth of his son Johann Heinrich states that he
is the first of first son of four children of the first wife. There is no record of his second wife, and when
he dies his death record states that there are this is that the survivors are his wife and three daughters and
one son. We don't have a death record for any of the children. So this is a bit of a mystery. I can check for
death records again. But one of the children may have married moved to a different village because her husband was from a different village and subsequently died. We just don't know.

In one of the birth records of one of the children the mother's surname is spelled differently, but she is clearly
the same person because their given names are the same as is her place of origin and the spelling is not
so different that it greatly differs in pronunciation.

In terms of the number of survivors after Jobst death, one or two of the children could have died. We just don't
know?


== Petzen Original Records Event Table for Jobst Heinrich Krückeberg Family

.Events based on xref:??
[cols="1,2,3,3,3,2,1,2,3a,4a,3a",options="header"]
|===
| Event Type
| Event Date
| Name of Subject
| Father
| Mother
| Residence / Village
| House Number
| Occupation
| Sponsors
| Notes
| Record Page

|Birth
|4 Aug. 1806
|Johann Heinrich Krückeberg
|Jobst Heinrich Krückeberg
|Christine Philippine Leonore Tegtmeier, from Evesen
|Bärenbusch
|10
|Schuster Amtsmeister (Shoemaker Guild Master)
|4^th^ child, 1^st^ son
|
|xref:petzen:PET-B-1806a.adoc[]

|Baptism
|17 Aug. 1806
|Johann Heinrich Krückeberg
|Jobst Heinrich Krückeberg
|Christine Philippine Leonore Tegtmeier, from Evesen
|Bärenbusch
|10
|Schuster Amtsmeister (Shoemaker Guild Master)
|
. Carl Friedrich Gottlieb Krückeberg, Einlieger in Bärenbush
. C Friedrich Tegtmeier from Meinsen
|
|xref:petzen:PET-B-1806a.adoc[]
|===
