= Merging the Two Krückeberg Lines

From his xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[Immanuel Lutheran
biography], we are given the names of the parents of Johann Heinrich Krüceberg, who
immigrated to Union, Adams CO IN in 1849, and we are provided the information
of all church ceremonies involving him, his wife and his children. We are
also provided the name of the parish, Petzen.

We likewise know the same information about Carl Friedrichm Krückeberg from
his xref:derived-church-records:FS-CSK.adoc["family record"]. We also have
the Immanuel Lutheran
xref:immanuel:ROOT:DEC-BIO-Krueckeberg-02.adoc[biography of his son],
Carl Heinrich Wilhelm, who was 15 when he arrived in the U.S.

Using these document we can construct the family of origin of both Johann Heinrich
and Carl Friedrich Krückebergusing the Petzen church records.

== How no. 18 Berenbusch Connects Johann Heinrich and Carl Friedrich

The father of Johann Heinrich Krückeberg, Jobst Heinrich,
xref:nla:146:doc1.adoc[petitioned the Schauburg-Lippe Rentkammer] in September
of 1808 to be granted a new holding in Berenbusch. They granted his request and
created the xref:NLA:146:doc6.adoc[new holding no. 18 at Berenbusch].

This information comes xref:nla:146:doc6.adoc[document #6] from the case file
link:https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4979522[NLA BU
K 2 B Nr. 146] located in the Bückeburg department of the Niedersächishces Landesarchiv
and denotated *Die Stätte Nr. 18 zu Berenbusch (the Holding no. 18 at Berenbusch)*.

From this case file and from the case file xref:NLA:120:[NLA BU, L 120a, D Nr. 188] denotated *Verkauf der
Krückebergschen Stätte Nr. 18 in Berenbusch an den Schuster Wilhelm Meyer zu
Röcke*


 XXX that Carl Friedrich came to own Stätte no. 18 at Berenbusch which was
first created and granted to Johann Heinrich's father in 180?.


TODO: Quote the archival documents 
Furthermore, the Bückeburg case files XXXX and XXX tell us that Carl Friedrich and Johann Heinrich were related and
thus share a common ancestor.  

