= Merging the Two Krückeberg Lines

From Johann Heinrich Krueckeberg's
xref:immanuel:ROOT:DEC-BIO-Krueckeberg-01.adoc[Immanuel Lutheran
biography], we are given the names of his parents, who immigrated to
Union, Adams CO IN in 1849, and we are provided the information of all
church ceremonies involving him, his wife and his children. We are also
provided the name of the parish, Petzen.

We likewise know the same information about Carl Friedrichm Krückeberg
from the xref:derived-church-records:FS-CFK.adoc["family record of the
emigrant Carl Friedrich Krückeberg"]. We also have the Immanuel Lutheran
xref:immanuel:ROOT:DEC-BIO-Krueckeberg-02.adoc[biography of his son, Carl
Heinrich Wilhelm], who was 15 when he arrived in the U.S.

Using these document we can construct the family of origin of both Johann Heinrich
and Carl Friedrich Krückebergusing the Petzen church records.

== No. 10 Berenbusch Home of Johann Heinrich Krückeberg

No. 10 Berenbusch is where the Jobst Heinrich Krückeberg family resided as
shown by the numerous Petzen church register xref:genealogy:ancestry:josbst-hk-1765.adoc[records
of its family members], all exclusively listing no. 10 Berenbusch as the - TODO: list all
of the village/ort references here: Wohnorot, Dortschaften.

We know from case file link:[NLA BU, K 2, A Nr. 689] denotated "200 Reichtsthaler.. "
No. 10 Be

It is also where the Colon Krückeberg lived who petitioned the Rentkammer 
in to xref:nla:139:krueckeberg-petition-to-sell.adoc[sell his holding
at no. 10 Berenbusch] explaining

[quote, TODO add source]
____
Ich bin willens, meine Kolonie zu verkaufen und nach Amerika auszuwandern...

I have decided to sell my farmstead and to emigrate to America...
____

Although his given names are not mentioned and he is only identified as "Colon
Krückeberg", we know this is Johann Heinrich because it is he and his family who
emigrated from Berenbusch in this same year and xref:immanuel:DEC-BIO-Krueckeberg-01[settle
in Union township, Adams CO, Indiana].

TODO: quote information for the other 139 documents that add more details that also help
to confirm the identity of Johann Heinrich like the xref:nla:139:doc1.adoc[petition of his mother],
the widow of Jobst Heinrich, as well as add other important details.

TODO: We know his full name is not given in xref:nla:689:index[case file 689], but his late
father is described as owning money to Hempel and Sons, a leather goods store....

TODO: We know in another case file for a Berenbsuch Stätte there is a map showing that
a Krückeberg Stätte borders the individual the case file is about.

== How no. 18 Berenbusch Connects Johann Heinrich and Carl Friedrich

The father of Johann Heinrich Krückeberg, Jobst Heinrich,
xref:nla:146:doc1.adoc[petitioned the Schauburg-Lippe Rentkammer] in September
of 1808 to be granted a new holding in Berenbusch. They granted his request and
created the xref:nla:146:doc6.adoc[new holding no. 18 at Berenbusch].

This information comes xref:nla:146:doc6.adoc[document #6] from the case file
link:https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4979522[NLA BU
K 2 B Nr. 146] located in the Bückeburg department of the Niedersächishces Landesarchiv
and denotated *Die Stätte Nr. 18 zu Berenbusch (the Holding no. 18 at Berenbusch)*.

From this case file and from the case file
link:https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v11398990[NLA BU,
L 120a, D Nr. 188] denotated *Verkauf der Krückebergschen Stätte Nr. 18 in Berenbusch an
den Schuster Wilhelm Meyer zu Röcke (Sale of the Krückeberg holding no. 18
Berenbusch to shoemaker Wilhelm Meyer of Röcke)*, we know that Carl Friedrich
Krückeberg came to own no. 18 Berenbusch. We know this because in 1850 he
petitioned the Rentkammer to accept its sale to the buyer he had found, Wilhelm
Meyer. See these documents:

* xref:nla:146:carl-fried-supplication-to-sell.adoc[]
* xref:nla:120:abschrift-4386.adoc[].

Furthermore, in these documents Carl Friedrich the reason for the sale: he
wants to emigrated in order to join "his relatives who are doing well":

[quote, TODO add citation here]
____
Da ich beabsichtige, mit meiner ganzen Familie nach Amerika auszuwandern,
woselbst sich schon *mehre Anverwandte von mir befinden, denen es recht
gut geht*, so habe ich meine kleine Neubauer-Colonie No. 18 in Berenbusch
an den Schuhmacher Wilhelm Meier, gebürtig aus Evesen, derzeitß in Röcke
verkauft. 

Since I intend to emigrate with my entire family to America, *where several
relatives of mine are already living and are doing quite well*, I have
therefore sold my small Neubauer holding, No. 18 in Berenbusch, to the
shoemaker Wilhelm Meier, a native of Evesen, presently residing in Röcke
____

We know now for certain the Johann Heinrich and Carl Friedrich, who are only
a year apart in age, share a common ancestor because they are related.
