= Bleeke Records Confirmed
:page-role: wide

== Frille Church Register Duplicates

There are duplicate church registers for Frille in the Nord Rhein Westfalen archives. However,for the years 1831, 1832, and 1834, it includes only  births/deaths “on the estates in Frille (village) belonging to the Gerichtsamt Petershagen,” and not the whole Frille parish area. The Bleekes lived in Leteln which was outside the jurisdiction of Gerichtsamt Petershagen.

To locate thes duplicates go to https://www.archive.nrw.de/archivsuche, and naviage as follows:

[arabic,start="1"]
. Landesarchiv NRW Abteilung Ostwestfalen-Lippe →
. Personenstandsarchiv Westfalen-Lippe →
. Kirchenbuchduplikate, Zivilstands-, Juden- und Dissidentenregister →
. Regierungsbezirk Detmold →
. Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks Minden →
. Frille, Kreis Minden  →
. Kirchenbuchduplikate.

Link to: link:https://www.archive.nrw.de/archivsuche?link=VERZEICHUNGSEINHEIT-Vz_b09e24b8-82d3-4415-b28e-3f5eb4f9d820[Kirchenbuchduplikat der evangelischen
Gemeinde Frille, Kreis Minden]

