= Who are the parents the Krückeberg Children Born Between 1728 to 1750

There were seven Krückeberg children born between 1728 and 1750, but we have
only one recorded Krückeberg marriage that we know of prior to 1728, that of
xref:petzen:petzen-band1b-image36.adoc[Johann Henrich Krückeberg to Anna Marie
Vahlsing on September 28, 1727].

== Birth Records

The birth records for the children born between 1736 and 1750 do not list the
parents given names:

.Krückeberg Children born from 1728 to 1750
[cols="2a,1,2a"]
|===
|Infant's Name|Baptism Date|Parents Names

|xref:petzen:petzen-band1a-image140.adoc[]| July 7, 1728|His birth record states: +
[literal,subs="verbatim,quotes"]
....
*Johann Heinrich Krückebergs* aus Berenbusch Söhnlein Johann Friedrich getauft
....

Translation: +
[literal,subs="verbatim,quotes"]
....
Johann Friedrich, the son of Johann Heinrich Krückeberg from Berenbusch, was baptized.
....

|xref:petzen:petzen-band1a-image152.adoc[]|29 Jan. 1736|Krückeberg v. [B. B.] ein Töchterl[ein] tauft lassen (Krückeberg from Berenbusch had a daughter baptized.)
                                              
|xref:petzen:petzen-band1a-image157.adoc[]|11 Feb. 1739|His xref:petzen:petzen-band1b-image167.adoc[death record]
states: +
[literal,subs="verbatim,quotes"]
....
d 5t Novemb. Johann Wilhelm Krückeberg
     Patris Johann Heinrich Krückeberg aus Berenbusch
     Söhnlein begraben, alt 8 3/4 Jahr
....
Translation:
[literal,subs="verbatim,quotes"]
....
On the 5th of November, Johann Wilhelm Krückeberg,
son of Johann Heinrich Krückeberg from Berenbusch,
was buried, aged 8¾ years
....
                                              
|xref:petzen:petzen-band1a-image163.adoc[]|27 Dec. 1741|From her xref:petzen:petzen-band2-image239.adoc[death
record]: Sophie Marie Krückeberg, des Jobst Heinrich Krückeberg nachgelaßen, blindgebohrne Tochter (Sophie Marie
Krückeberg, surviving daughter of Jobst Heinrich Krückeberg, born blind

|xref:petzen:petzen-band1a-image167.adoc[]|19 Jan. 1744|

|xref:petzen:petzen-band1a-image174.adoc[]|26 Oct. 1746|

|xref:petzen:petzen-band1a-image180.adoc[]|4 Nov. 1750|

|todo||
|===

== Extremely Atypical Birth Pattern

The mother would have been ages 38, 43, 45 and 49, respectively, at the birth of her last four children. 
She would have been 49 at the birth her last child, which is not even believeable.

=== Comparision to Birth Patterns of Actual Mother's Age 40 and Above 

Children of JHP Bleeke and Anna Margaretha Volkening:

Carl Heinrich Bleeke born in 1818

Christian Friedrich Bleeke born in 1821

Carl Friedrich born 1821

Carl Friedrich Johann Wilhelm Bleeke born in 1825

Christine Marie Bleeke born in 1828

Christine Sophie Eleonore Bleeke born in 1830

Marie Luise Eleonore Bleeke born in 1833

Emilie Bleeke born in 1837


== Confirmation Records

*TODO:* There should be a confirmation record for Johann Fridrich, born July 1728, in the Petzen
link:https://www.archion.de/de/alle-archive/niedersachsen/niedersaechsisches-landesarchiv/kirchenbuecher-der-evangelisch-lutherischen-landeskirche-schaumburg-lippe/petzen/329073[Verzeichnis
der Getauften und Konfirmierten 1641-1784] of 1728 in approximately the years 1741 to 1743?

== Jobst Krückeberg

A Jobst Krückeberg was the father of Sophia Maria Kruekeberg, who was baptiyed in 1741; we know this from
her xref:petzen:petzen-band2-image239.adoc[death record] where her father is listed.
