= Completed Research by Dr. Möhle 

== Documents Reviewed

Dr. Sylvia Möhle examined these documents in the Bückeburg regional
archive of the Lower Saxony, Germany, State Archives:

[%header,cols="1,9a"] 
|===
|Life Span|Identifier

|1737 |Erfassung der Haus- und Hofbesitzer im Amt Bückeburg im Rahmen einer Generallandesvisitation (Landesvermessung)

Recording of house and farm owners in the Bückeburg district as part of a general land survey (state survey)

|1743-1744 |Protokolle über die Befragung der einzelnen Hofbesitzer in
Evesen, Berenbusch, Nordholz und Rusbend im Rahmen der Generallandesvisitation (Landesvermessung)

Records of the interviews with individual farm owners in Evesen, Berenbusch, Nordholz and Rusbend as part of the general land survey (land survey)

|1745 |Vermessung der Dörfer Evesen, Berenbusch und Nordholz

Survey of the villages of Evesen, Berenbusch, and Nordholz

|1747 |Namensverzeichnis sämtlicher Kolonen der Ämter Bückeburg und
Arensburg, mit Nummerierung der sämtlichen Häuser.

List of names of all Kolonen in the districts of Bückeburg and Arensburg, with numbering of all houses.
|===

Johann Heinrich Krückeberg first appears in the Petzen Kirchenbuch records
when he marries Anna Marie Vahlsing on
xref:petzen:PET-M-1727a.adoc[September 18, 1727].  According to their
marriage record:

* he is *"aus Berenbusch"*, and 
* she is *aus Evesen*. 

They remain married until she dies on xref:petzen:PET-D-1757b.adoc[May 8,
1757]. The following year, on xref:petzen:PET-M-1758a.adoc[September 29,
1758], he marries Ilse (Elisabeth) Margarethe Rösener. He, then, dies the
following year and is xref:petzen:PET-D-1759a.adoc[buried on December 26,
1759] age 55.

Johann Heinrich Krückeberg does not appear in the 1737
xref:nla:2728:survey-1737.adoc[] as the holder/owner (Besitzer) of no. 10
Berenbusch. He may have not met the criteria for inclusion.

He does appear in the 1743-1744 xref:nla:2741:index.adoc[].  His replies to
the questions--which were unfortunately not preserved--are below:

[literal.bordered,subs="verbatim,quotes"]
....
N. X [Rf?] er hiesse

1. Johann Henrich Krückeberg

vormahls Friedrich Kuhlmann auch

Joh. Tönnies Eggerding

2. habe darauf geheyrahtet

3. ein Brinksitzer

4. Er habe nichts als einen Garten

worin zugl. etwas Saatlandt

Nach der neuen Messung.

5. cessat

6. er habe kein Rottland ausser

dem Garthen

7. Sey Illmo eigen.

8. Wöchentl. Dienste verrichte er [symbol = nicht; old code for
‚not‘]

9. jährl. 12 Burgfesten

10. cessat

11. funff Erndte Tage

12. so offt es nöhtig

13. so offt es erforderlig [bei anderen: Landfolge mit der Hand]

14. 15. 16. ut reliqui [bei anderen: auch Jagd und Wachten]

17. cessat

18. [Dues]

a) contribat 2 [Groschen] 2 [Pfennige]

b) Rottzinß 11 [Groschen]

c) Mahl[...] 12 [Groschen]

d) Michael Schatz cessit

e) –

f) – 4 [Pfennige]

g) Landschatz gibt er nicht weilen

er kein Land habe

h) nescit

i) ut reliqui

k) Viehschatz p nro. des Viehes

4 mgr [Groschen] 4 Pf [Pfennige] auch 8 mgr [Groschen]

l) cessat

m) Ein Rauchhuhn an gdste Herrschafft

n) nescit

19)

a) ut reliqui

b) Erbe 3 rthlr [Taler] 4 mgr [Groschen] 4 Pf [Pfennige]

c-g nescit

20-23 cessat

24. 1 Kuh 1 Rind

1 Schwein

25. treibe solche vor den Hirten

26. nein

27-31 cessat

32. Er gebe niemand

etwas als dem

pastori und Küster

das gewöhnliche

33. nein

34. Vermeyne, da er

keine Länderey

habe, solche nicht

schuldig zu seyn

35. nein

*36., 37.* cessat

38. nein

39. ut reliqui

40. Er samle

das Holtz in

der Waldung

oder kauffe es.
....

His first reply gives *Friedrich Kuhlman* as the prior holder of no. 10
Berenbusch, and before him the holder was *Johann Tönnis Eggerding*.

The 1745 "Vermessung der Dörfer Evesen, Berenbusch und Nordholz" also shows
he is the Besitzer (holder) of no. 10 Berenbusch. Belows is the content of
page 110 where Johann Heinrich appears:

[literal.bordered]
....
p 110 Berenbusch: 
No. 10 am Hause
Johann Henrich Krickeberg zu Behrenbusch
besitzet
An Hoff und Gartenland
Der Hoff darauf stehet ein Wohnhaus
Derselben hält                     -               6 [Ruten]
Ein Garten bey dem Hause  hat      ¾ [Morgen]     23 [Ruten]
Summa Summarum                     ¾ [Morgen]     29 [Ruten] [nach neuer Messung]
....

which translates as

[literal.bordered]
....
No. 10 at the house
Johann Henrich Krickeberg in Behrenbusch
owns
Farmyard and garden land
The farmyard has a residential building on it
It covers 6 rods
A garden next to the house  has    ¾ [acre]    23 [rods]
Total                              ¾ [acre]    29 [rods] [according to new measurement]
....

On page 17 of the 1747 *Namensverzeichnis sämtlicher Kolonen der Ämter
Bückeburg und Arensburg, mit Nummerierung der sämtlichen Häuser ("List of
names of all colonists in the districts of Bückeburg and Arensburg, with
numbering of all houses")* the following information appears about the
current and former holder of No. 10 Berenbusch.

[NOTE]
====
"modo" means: *“now”*, *“at present”*, *“currently”* or *“in the possession
of”*.
====

[literal.bordered,subs="verbatim,quotes"]
....
Joh. Heinr. Kreutler modo Daniel Steding

     Brinksitzer

5.) Joh. Kohlmeier modo Joh. Friedr. Kohlmeier
6.) Jobst Heinr Jacob modo Jobst Jacob.
7.) Anthon Heinr. Bornemann modo Joh. Jobst Most.
8.) Ahrend Heinr. Ostermeier modo Joh. Heinr: Bornemann
9.) Cord Heinr. Wilharm modo Joh. Heinr. Schmön
10.) Joh. Tönnies Eggerding modo *Joh. Heinr. Kruckeberg*
11.) Hans Heinr. Riensche und ein neuer Anbauen

         Dorf Nodholz
....

Other facts to know:

* Johann Tönnis Eggerding, a former holder of no. 10 Berenbusch, was a
  baptismal sponsor of Johann Heinrichäs son, Johann Friedrich, who was
born in 1728.
* Johann Heinrich Krückeberg's first wife, who lived until 1757, was the
  daughter of a sheperd from Evesen.
