= Dr. Möhle's Completed Research 

== Background /Timeline

On xref:petzen:PET-M-1727a.adoc[September 18, 1727], Johann Heinrich Krückeberg 
marries Anna Marie Vahlsing in the Petzen parish. According to the marriage
record he is *aus Berenbusch* ("from Berenbusch"), and she is *aus Evesen*
("from Evesen").

A 1757 Petzen burial record notes an *Anna Maria Krückeberg age 56* was
xref:petzen:PET-D-1757b.adoc[buried on May 8, 1757].

On xref:petzen:PET-M-1758a.adoc[September 29, 1758], *Johan Henr. Krückeberg*
marries *Ilse (short for Elisabeth) Margarethe Rösener*. He, then, dies the
following year and is xref:petzen:PET-D-1759a.adoc[buried on December 26,
1759] age 55.

Johann Heinrich Krückeberg does not appear in the 1737
xref:nla:2728:survey-1737.adoc[] as the holder/owner (Besitzer) of no. 10
Berenbusch. He may have not met the criteria for inclusion.

He does appear in the 1743-1744 xref:nla:2741:index.adoc[].

His first reply gives *Friedrich Kuhlman* as the prior holder of no. 10
Berenbusch, and before him the holder was *Johann Tönnis Eggerding*.

*TODO:* Are there any other key bits of information from his replies that
are inportant?

The 1745 xref:nla:2713:index.adoc[] also shows he is the Besitzer (holder)
of no. 10 Berenbusch. Belows is the content of page 110 where Johann
Heinrich appears:

[literal.bordered]
....
p 110 Berenbusch: 
No. 10 am Hause
Johann Henrich Krickeberg zu Behrenbusch
besitzet
An Hoff und Gartenland
Der Hoff darauf stehet ein Wohnhaus
Derselben hält                     -               6 [Ruten]
Ein Garten bey dem Hause  hat      ¾ [Morgen]     23 [Ruten]
Summa Summarum                     ¾ [Morgen]     29 [Ruten] [nach neuer Messung]
....

which translates as

[literal.bordered]
....
No. 10 at the house
Johann Henrich Krickeberg in Behrenbusch
owns
Farmyard and garden land
The farmyard has a residential building on it
It covers 6 rods
A garden next to the house  has    ¾ [acre]    23 [rods]
Total                              ¾ [acre]    29 [rods] [according to new measurement]
....

