= Dr. Möhle's Completed Research 

== Background

On xref:petzen:PET-M-1727a.adoc[September 18, 1727], Johann Heinrich Krückeberg 
marries Anna Marie Vahlsing in the Petzen parish. According to the marriage
record he is *aus Berenbusch* ("from Berenbusch"), and she is *aus Evesen*
("from Evesen").

A 1757 Petzen burial record notes an *Anna Maria Krückeberg age 56* was
xref:petzen:PET-D-1757b.adoc[buried on May 8, 1757].

On xref:petzen:PET-M-1758a.adoc[September 29, 1758], *Johan Henr. Krückeberg*
marries *Ilse (short for Elisabeth) Margarethe Rösener*. He, then, dies the
following year and is xref:petzen:PET-D-1759a.adoc[buried on December 26,
1759] age 55.

Johann Heinrich Krückeberg does not appear in the 1737 *Registration of
house and farm owners in the Bückeburg district as part of a general state
inspection ("Erfassung der Haus- und Hofbesitzer im Amt Bückeburg im Rahmen
einer Generallandesvisitation")* as the holder/owner (Besitzer) of no. 10
Berenbusch. He may have not met the criteria for inclusion.


