= Petzen and Frille Bückeburg Archive Research

== Frille Volumes

The Frille volumes are apparently transcripts of the Frille church registers. I assume they are already
in contemporary German and not the old _Kurrent_ handwritting. While they are not the original source, the
original church registers (Kirchenbücher), they should be consulted first. The original church registers 
are not listed in link:https://www.arcinsys.niedersachsen.de/[Arcinsys] catalog.

To view any of these volumes in person in the Bückeburg archive, follow these steps:
[arabic,start="1"]
. Create an Arcinsys Account:
** Go to link:https://www.arcinsys.niedersachsen.de/arcinsys/start.action?oldNodeid=[Arcinsys for Niedersachen and
Bremem].
** In upper right corner: Login -> Register
. Login to to your link:https://www.arcinsys.niedersachsen.de/arcinsys/start.action?oldNodeid=[Arcinsys account]
. Click on the call number of the volume in the table below.
. Bookmark it within Arcinsys (you must be logged in to bookmark items)
. After you have bookmarked all the volumes you desire, go to
link:https://www.arcinsys.niedersachsen.de/arcinsys/nutzer/merkzettel.action[Memo List] to view them. *Memo List* is
one of the tabs at the top of every page.
. Add to view in person an item in your Memo List, click *"into the order basket"*. This will reserve it for the date you supply.

=== Church Register Duplicates

From: https://www.archive.nrw.de/archivsuche, naviage to: +
Landesarchiv NRW Abteilung Ostwestfalen-Lippe -> Personenstandsarchiv Westfalen-Lippe -> 
Kirchenbuchduplikate, Zivilstands-, Juden- und Dissidentenregister -> Regierungsbezirks Minden -> 
Frille, Kreis Minden -> Zivilstandregister AND -> Kirchenbuchduplikate

Link to: link:https://www.archive.nrw.de/archivsuche?link=VERZEICHUNGSEINHEIT-Vz_b09e24b8-82d3-4415-b28e-3f5eb4f9d820[Kirchenbuchduplikat der evangelischen
Gemeinde Frille, Kreis Minden]


== Individuals

=== Bleeke

[[bleeke-marriages]]
==== Confirmed Marriages

.Bleeke Marriage Dates Confirmed:
|===
|Groom|Bride|Marriage Date|URL to Actual Record

|Carl Fridrich Bleeke
|Marie Luise Niemann 
|March 12, 1820
|link:https://dfg-viewer.de/show?tx_dlf%5Bdouble%5D=0&tx_dlf%5Bid%5D=https%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Ostwestfalen-Lippe%2FP1%2FB%2F~001%2FB00168_01_1815-1830%2Fmets.xml&tx_dlf%5Bpage%5D=70&cHash=507bb1dc0865977ffd9ef86d2c566618[Abt.
Ostwestfalen-Lippe, P 1 B (Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks Minden), Nr. 168
_01_Jg. 1815-1830, image 70 of 180, Nro #4].

|Johann Heinrich Philipp Bleeke
|Christine Maria Schwier
|Spring of 1819
|link:https://dfg-viewer.de/show?tx_dlf%5Bdouble%5D=0&tx_dlf%5Bid%5D=https%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Ostwestfalen-Lippe%2FP1%2FB%2F~001%2FB00168_01_1815-1830%2Fmets.xml&tx_dlf%5Bpage%5D=71&cHash=379e9317c05c2c014792c3beeafba9b1[Abt.
Ostwestfalen-Lippe, P 1 B (Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks Minden), Nr. 168
_01_Jg. 1815-1830, image 71 of 180, Nro 9]


|Christian Friedrich Bleeke
|Christine Luise Eloenore Krückeberg
|Nov 26, 1826
|link:https://dfg-viewer.de/show?tx_dlf%5Bdouble%5D=0&tx_dlf%5Bid%5D=https%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Ostwestfalen-Lippe%2FP1%2FB%2F~001%2FB00168_01_1815-1830%2Fmets.xml&tx_dlf%5Bpage%5D=133&cHash=6e4114964fb631e8582fa0aa92d1b190[Abt.
Ostwestfalen-Lippe, P 1 B (Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks Minden), Nr. 168
_01_Jg. 1815-1830, image 133 of 180, Nro 7]
|===

=== Confirmed Dates of Bleeke Children's Birth and Baptism

.Children of Johann Heinrich Philip Bleeke and Christine Luise Schwier
|===
|Child|Birth Date|Legitimate or Illegitimage|URL to Actual Record

|Carl Heinrich Bleeke
|27 April 1818
|illegitimate, 1^st^ child, 1^st^ son
|https://dfg-viewer.de/show?tx_dlf%5Bdouble%5D=0&tx_dlf%5Bid%5D=https%3A%2F%2Fwww.landesarchiv-nrw.de%2Fdigitalisate%2FAbt_Ostwestfalen-Lippe%2FP1%2FB%2F~001%2FB00168_01_1815-1830%2Fmets.xml&tx_dlf%5Bpage%5D=40&cHash=90b3e7f90b94cba63ceaeaba37f85eb5[Abt.
Ostwestfalen-Lippe, P 1 B (Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks Minden), Nr. 168
_01_Jg. 1815-1830, image 40 of 180, Nro 16]
|===

