= 1712 Anthon Henrich Vahlsing Baptism

[.narrow]
== Citation

The June 19, 1712, baptism of Anthon Henrich Vahlsing is on <<PET-B-1712b,
image 120>>, the first entry of the right-hand page in the
Petzen "Verzeichnis der Getauften und Konfirmierten 1641-1784" on
link:https://archion.de[Archion.de].


== Transliteration and Translation

.Transliteration
[literal.bordered,subs="verbatim,quotes"]
....
17 den 19 Juni ist Henrich Arendt Vahlsings Schäfers auf Hockersau
Söhnlein Anthon Henrich getauf Gev. Henri. Weitzenkorn
....

.Translation
[literal.bordered,subs="verbatim,quotes"]
....
17 the 19th June was Henrich Arendt Vahlsing's, shepherd at Hockersau,
little son, Anton Henrich, baptized. Sponsor Henrich Weitzenkorn. 
....


[bibliography]
== Citations

* [[[PET-B-1712b]]] "Archion Protestant Kirchenbücher Portal", database
with images, Archion (https://www.archion.de/p/84a3ff6f9c/ : 16 February
2026), path: Niedersachsen > Niedersächsisches Landesarchiv > Kirchenbücher
der Evangelisch-Lutherischen Landeskirche Schaumburg-Lippe > Petzen >
Verzeichnis der Getauften und Konfirmierten, 1641-1784 > Image 120 of 322
