= Carl Friedrich Bleeke 1823 Birth
:page-role: wide

This record is from the ???
link:https://www.archive.nrw.de/archivsuche?link=VERZEICHUNGSEINHEIT-Vz_b09e24b8-82d3-4415-b28e-3f5eb4f9d820&mandant=10003[Landesarchiv
NRW Abteilung Ostwestfalen-Lippe / P 1 B-D / Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks
Minden, Nr. B 168 Jg. 1815-1830].

image::

.Transliteration of 
[cols="1l,4l,4l,2l,4l,4l,3l,2l,3l,5l"]
|===
10+^s|Geborene und Getaufte im Jarhe 1823

s|Nro.
s|Tauf-Name
des Kindes.
s|Tag und Stunde
der Geburt
in
Buchstaben und Ziffern.
s|Ob es
ehelich
oder
unehelich.
s|Vor- and Zuname
des Vaters,
auch Stand desselben
s|Vor- und Zuname
der
Mutter.
s|Wohnort
der
Eltern
s|Tag
der
Taufe.
s|Namen des Predigers,
der es getauft.
s|Name der Taufzeugen
|
|
|
|
|
|
|
|
|
|
|===

.Translation of 
[cols="1,4,4,2,4,4,3,2,3,5"]
|===
10+^s|Born and Baptized in the year 1823

s|No.
s|Baptismal name of the child.
s|Day and hour of birth (in words and numbers)
s|Whether legitimate or illegitimate
s|Given and surname of the father, also his Status
s|Given and surname of the mother
s|Residence of the Parents
s|Day of baptism
s|Name of the minister
s|Baptismal witnesses

|
|
|
|
|
|
|
|
|
|
|===

== Citation

TODO: Fix

Evangelische Gemeinde Frille (Kreis Minden), Kirchenbuchduplikate, section headed "Gebohrne u Getaufte im Jahre
1823" [sic], Nr. 29, Carl Fried. Bleeke, born 10 July 1823, baptized 20 July 1823, son of Johann Heinrich Bleeke
and Christine Marie Schwier; Landesarchiv Nordrhein-Westfalen, Abteilung Ostwestfalen-Lippe (Detmold),
Personenstandsarchiv Westfalen-Lippe; P 1 B-D, B 168 (Jg. 1815–1830); digital images, Archivsuche – Archive in NRW
(DFG-Viewer), Bild 100/180 (accessed 18 September 2025); duplicate register; provenance: Land- und Stadt- bzw.
Kreisgericht Minden.
