= Bleeke Records

The Bleeke church records come from these sources:
[arabic,start=1]
. The Archion Frille volumes:
** Verzeichnis der Getauften, Getrauten, Gestorbenen 1664-1757
** Verzeichnis der Getauften, Getrauten, Gestorbenen 1758-1804
. These Frille Kirchenbuchduplikate:
** link:https://www.archive.nrw.de/archivsuche?link=VERZEICHUNGSEINHEIT-Vz_b09e24b8-82d3-4415-b28e-3f5eb4f9d820&mandant=10003[Landesarchiv
NRW Abteilung Ostwestfalen-Lippe / P 1 B-D / Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks
Minden, Nr. B 168 Jg. 1815-1830]
** link:https://www.archive.nrw.de/archivsuche?link=VERZEICHUNGSEINHEIT-Vz_0248b6a4-ed8c-41ef-8e2b-f61ac1448763[Landesarchiv
NRW Abteilung Ostwestfalen-Lippe / P 1 B-D / Kirchenbuchduplikate und Zivilstandsregister des Regierungsbezirks
Minden, Nr. B 168 Jg. 1831-1845].
. The link:http://hdl.handle.net/2374.UC/753629[online PDF] of the 1814-1848 church register of the *Nord deutschlische
lutheranische Kirche* (*German Evangelical Lutheran and Reformed Church*) found in the Archives and Rare Books
Library, University of Cincinnati.  
. TIF images of the church register of Immanuel Lutheran Church, Decatur, Indiana.


