= Johann Heinrich Wilhelm Carl Grote

== Transliteration from old German script

page 33

No. 3

Sohn von Heinrich Grote und Sophie geborene Barnekamp, geb. den 4
November 1823 in Jenhorst, Amt Stolzen (Stolzenau), Königreich Hannover,
get. den 9 November 1823 in der ev. luth. Kirche zu Nenndorf
(Samtgemeinde Nenndorf) von Pastor Müller, confirmiert um Ostern 1837
von Pastor Lindemann, ausgewandert nach den Ver. St. v. N.A. den 8 Sept.
1849, gelandet in New York den 20 Nov. s.J., und nachdem er dort wie
auch in Fort Wayne und in Preeple (Preble) Tow. Adams Co. Ind. eine
Zeitlang gearbeitet hatte, verheirathete er sich den 11 Juni 1852 mit
Jungfrau xref:DEC-BIO-Krueckeberg-01.adoc#cpd-krueckeberg[Caroline Philippine Dorathea Krückeberg] dahier (siehe die
vorige Seite, Kind 1) und ließ sich zu derselben Zeit in dieser Gemeinde
nieder, der er sich auch alsbald anschloß.

Kinder dieser Ehe sind:

1. Carl Heinrich Christian, geb. den 26 Febr. u. getauft den 12
März d. s. Jahres 1853. Taufpathen: Heinrich Krückeberg und Christian
Bleeke

2. Caroline Christine Sophie, geb. den 9 April u. getauft den 29
April 1855. Taufpathen: Caroline Grote, Philippine Krückeberg, Leonore
Bleeke.

3. Caroline Christini, geb. den 11 Sept. u. get. den 4 October
1857\. Taufpathen: Christine Krückeberg und Philippine Schamerloh.

4. Carl Wilhelm Christian, geb. den 15 Sept. u. get. den 6
October 1860. Taufpathen: Carl Nürge und Christian Schamerloh. Gestorben
den 2 Januar 1862.

5. Wilhelmine Louise, geb. den 23 Sept und get. den 12 October
1862\. Taufpathen: Wilhelmine Nürge und Wilhelmine Weiland.

6. Wilhelmine Christine, geb. den 12 März und getauft den 20
März. 1865. Taufpathen: Wilhelmine Weiland und Caroline Schamerloh.

== English Translation

page 33

No. 3

Johann Heinrich Wilhelm Carl Grote

Son of Heinrich Grote and Sophie neé Barnekamp. He was born on 4
November 1823 in Jenhorst, parish district of Stolzen (Stolzenau),
Kingdom of Hannover, baptized on 9 November 1823 in the Protestant
Lutheran Church in Nenndorf (Samtgemeinde Nenndorf) by Pastor Müller,
and confirmed around Easter 1837 by Pastor Lindemann.

He emigrated to the United States of North America on 8 Sept. 1849, and
arrive in New York on 20 Nov. of the same year. After he worked for a
while there as well as in Fort Wayne and in Preeple (Preble) Township,
Adams County, Ind., he married here on 11 June 1852 the maiden Caroline
Philippine Dorathea Krückeberg (see previous page, child No. 1). He also
settled here at the same time and soon after joined the parish
community.

Children of this marriage are:

1. Carl Heinrich Christian, born on 26 February 1853, and
baptized on 12 March of the same year. Godparents: Heinrich Krückeberg
and Christian Bleeke.

2. Caroline Christine Sophie, born on 9 April, and baptized on 29
April 1855. Godparents: Caroline Grote, Philippine Krückeberg, Leonore
Bleeke.

3. Caroline Christini, born on 11 September, and baptized on 4
October 1857. Godparents: Christine Krückeberg and Philippine
Schamerloh.

4. Carl Wilhelm Christian, born on 15 September and baptized on 6
October 1860. Godparents: Carl Nürge and Christian Schamerloh. Died on 2
January 1862.

5. Wilhelmine Louise, born on 23 Sept, and baptized on 12 October
1862\. Godparents: Wilhelmine Nürge and Wilhelmine Weiland.

6. Wilhelmine Christine, born on 12 March, and baptized on 20
March 1865. Godparents: Wilhelmine Weiland and Caroline Schamerloh.
