= Christian Fridrich Bleeke

== Transliteration

Download xref:attachment$christian-fridrich-bleeke.jpg[original image of biography]

No. 10

zweiter Sohn von xref:DEC-BIO-Bleeke-01.adoc[Johann Heinrich Philipp Bleeke] und Christine Marie neé
Schwier, geb. den 7. Mai und get. den 13. Mai 1821 (siehe Seite 31, Kind
No.2). Er verheiratete sich den 9. August 1849 mit Jungfrau Louise
Valsing, eine Tochter von Friderich Valsing und seiner Ehefrau Louise
geb. (in pencil: Kleinschmidt Friedheim) den 28. Juni 1833, und get. den
[empty] August 1833. Geb. in Loh (now: Am Loh) Kreis Minden, Königreich
Preussen.

Kinder dieser Ehe sind:

1. Marie Louise, geb. den 14. November u. get. den 8.Dezember 1850.
Pathen: Wilhelmine Zwick und Sophie Heckmann.

2. Sophie Louise, geb. den 27. März und get. den 28. März 1853.
Pathen: Christine Bleeke, Christine E. Bleeke und Louise Valsing.

3. Johann Heinrich, geb. den 17. Februar u. get. den 25. Februar 1855.
Pathen: Johann Heinrich Bleeke und Friedrich Valsing.

Im Jahre darauf ging die Mutter dieser Kinder nach kurzem Leiden am
Nervenfieber ein zu ihres Herrn Freude. Ihm Jahre 1858 den 8 April
verheirathete genannter Chr. Fr. Bleeke sich zum andern Male mit
Jungfrau: Anna Maria Rup, eine Tochter von Rup und [empty] geb. den 11.
Sept. 1833 u. get. [empty], ( note in pencil: died 26 Nov. 1989), in
[empty] Co, Ohio confirmiert.

1. Christine Elise, geb. den 1. Februar u. get. den 27 Februar 1859.
Pathen: Elisabeth Rup u. Christine Heckmann, gest. den 6 April 1861

2. Maria Elise, geb. den 23 Juni u. get. den 8 Juli 1860. Pathen:
Maria Reinking und Sahra Rup.

3. Carl Friedrich, geb. den 1 Oktober u. get. den 9 Oktober 1863.
Pathen: Carl Zwick und Carl Heckmann.

4. Friedrich Wilhelm, geb. den 2 Oktober u. get. den 9 Oktober
1863\. Pathen: C. Friedrich Wilhelm Bleeke und Ferdinand Reinking.

5. Johannes Martin, geb. den 27 Juli u. get. den 13 September
1865\. Pathen: Wilhelm Fells und Wilhelm Heckmann.

== English Translation

No. 10

Christian Fridrich Bleeke

2^nd^ son of xref:DEC-BIO-Bleeke-01.adoc[Johann Heinrich Philipp Bleeke] and Christine
Marie neé Schwier, born on 7 May and baptized on 13 May 1821 (see page 31, child
No.2). He married 9 August 1849 the maiden Louise Valsing, a daughter of
Friderich Valsing and his wife Louise neé (in pencil: Kleinschmidt Friedheim),
who was born 28 June 1833, and baptized [empty] August 1833. She was born
in Loh (now: Am Loh) county of Minden, Kingdom of Prussia.

Children from this marriage are:

1. Marie Louise, born 14 November, and baptized 8 December 1850.
Godparents: Wilhelmine Zwick and Sophie Heckmann.

2. Sophie Louise, born 27 March and baptized 28 March 1853.
Godparents: Christine Bleeke, Christine E. Bleeke, and Louise Valsing.

3. Johann Heinrich, born 17 February, and baptized 25 February 1855.
Godparents: Johann Heinrich Bleeke and Friedrich Valsing.

In the following year, after a short period of suffering from nervous
fever (usually typhoid fever), the mother of these children went home to
her Lord and was joyfully received by Him. On April 8, 1858, the above
mentioned Chr. Fr. Bleeke married again. He married the maiden Anna
Maria Rup, a daughter of [empty] Rup and [empty]. She was born 11
September 1833, and baptized [empty], in [empty] County, Ohio, and
confirmed [empty]. (note in pencil: died 26 Nov. 1889),

1. Christine Elise, born 1 February, and baptized 27 February 1859.
Godparents: Elisabeth Rup and Christine Heckmann; died 6 April 1861.

2. Maria Elise, born 23 June, and baptized 8 July 1860.
Godparents: Maria Reinking and Sahra Rup.

3. Carl Friedrich, born 1 October, and baptized 9 October 1863.
Godparents: Carl Zwick and Carl Heckmann.

4. Friedrich Wilhelm, born 2 October, and baptized 9 October 1863.
Godparents: C. Friedrich Wilhelm Bleeke and Ferdinand Reinking.

5. Johannes Martin, born 27 July, and baptized 13 September 1865.
Godparents: Wilhelm Fells and Wilhelm Heckmann.
