= Carl Fridrich Wilhelm Bleeke

== Transliteration

Download xref:attachment$07-carl-friedrich-wilhelm-bleeke.jpg[original image of biography]

No. 7

dritter Sohn von xref:DEC-BIO-Bleeke-01.adoc[Johann Heinrich Philipp Bleeke] und Christine Marie geb.
Schwier, geb. den 30. November und getauft den 4. Dezember 1825 (siehe
Seite 31, Kind No.4). Er verheiratete sich hierselbst mit Maria
Bibelheimer, eine Tochter von David Daniel Bibelheimer und Maria geb.
Zähner, geboren in Wespen Tow. (West Penn?) Shulkil (Schuylkill) Co. Pa.
den 12. Dezember 1833, getauft den 1. January 1834. Taufpathen: David
Werdmann und dessen Frau Catharina. Confirmiert von Pastor Fritze den 28
Juli 1852, copuliert von demselben den 26. Dezember 1853.

Kinder dieser Ehe sind:

1. Friedrich Wilhelm, geb. den 13. April u. get. den 29. April 1855.
Pathen: Johann Heinrich Bleeke, Christian Fridrich Bleeke und
Wilhelm Heckmann.

2. Maria Christine Caroline, geb. den 4. Dezember u. get. den 7.
Dezember 1856. Pathen: Maria Louise Eleoenore Reinking und Caroline
Scheumann. gest. den 18. Oktober 1857.

3. Maria Louise, geb. den 4. März u. get. den 28. März 1858.
Pathen: Maria Bibelheimer und Sophie Heckmann.

4. Caroline Elisabeth, geb. den 1. November u. get. den 20.
November 1859. Pathen: Elisabeth Bibelheimer und Maria Bleeke

5. Christine Emilie, geb. den 8. September u. get. den 29
September 1861. Pathen: Christine Maria Heckmann und Caroline Scheumann.

6. Christian Eduard, geb. den 5. November und get. den 29. Nov. 1863.
Pathen: Chr. Fridrich Bleeke, David Daniel Bibelheimer und Carl
Heckmann.

7. Henriette Helene, geb. den 29. Oktober und getauft den 12.
November 1865. Pathen: Louise Maria Eleonore Reinking und Henriette
Schnellenberger.

== English Translation

No. 7

Carl Fridrich Wilhelm Bleeke

Third son of xref:DEC-BIO-Bleeke-01.adoc[Johann Heinrich Philipp Bleeke] and Christine Marie neé
Schwier. He was born on the 30^th^ of November and baptized on December
4^th^ 1825 (see page 31, child No.4). He married here Maria Bibelheimer,
a daughter of David Daniel Bibelheimer and Maria neé Zähner. She was
born in Wespen Township (West Penn?) Shulkil (Schuylkill) County, PA, on
December 12^th^ 1833, and baptized on January 1^st^ 1834. Godparents:
David Werdmann and his wife Catharina. She was confirmed by Pastor
Fritze on July 28^th^ 1852, and married by the same on December 26^th^
1853.

Children from this marriage are:

1. Friedrich Wilhelm, born on 13 April, and baptized on 29 April 1855.
Godparents: Johann Heinrich Bleeke, Christian Fridrich Bleeke, and
Wilhelm Heckmann.

2. Maria Christine Caroline, born on 4 December, and baptized on
7 December 1856. Godparents: Maria Louise Eleoenore Reinking and
Caroline Scheumann. She died on 18 October 1857.

3. Maria Louise, born on 4 March, and baptized on 28 March 1858.
Godparents: Maria Bibelheimer and Sophie Heckmann.

4. Caroline Elisabeth, born on 1 November, and baptized on 20
November 1859. Godparents: Elisabeth Bibelheimer and Maria Bleeke

5. Christine Emilie, born on 8 September, and baptized on 29
September 1861. Godparents: Christine Maria Heckmann and Caroline
Scheumann.

6. Christian Eduard, born on 5 November, and baptized on 29 Nov. 1863.
Godparents: Chr. Fridrich Bleeke, David Daniel Bibelheimer, and
Carl Heckmann.

7. Henriette Helene, born on 29 October, and baptized on 12
November 1865. Godparents: Louise Maria Eleonore Reinking and Henriette
Schnellenberger.
