= Johann Heinrich P. Bleeke

== Transliteration

Download xref:attachment$jhp-bleeke.jpg[original image of biography]

page 31

No. 1

Sohn von Fridrich Bleeke und Anna Margaretha geb. Volkening, geb. zu
Leeteln (Leteln), Kanton Windheim, Kreis Minden, Königr. Preussen, den 3
November und get. im selben Monat 1797 von Past. Peikmann. Sein
Taufpathe war Johann Fridrich Volkening; confirmiert am Sonntage nach
Ostern 1810.

Er verheiratete sich im Frühling 1819 mit Christine Maria Schwier, eine
Tochter von Christian Fridrich Schwier und Catharina Margareta geb.
Rösner, geb. den 13 Mai und getauft im selben Monat 1798 in der ev.
luth. Kirche zu Frülle (Frille) von Past. Peikmann. Pathen: Anna Sophie
Rösner und Christine Müller; confirmiert am Sonntage nach Ostern 1811.

Im Jahre 1834 wanderte genannter Johann Heinrich Philipp Bleeke aus nach
den Vereinigten Staaten von N.-A., wohin ihn in den beiden
darauffolgenden Jahren seine Familie nachfolgte. Und nachdem er eine
Zeitlang bei Wheeling Va und in Cincinati (Cincinnati) O. gewohnt, zog
er in hiesige Gegend 1840, woselbst auf seinen Betrieb im Jahre 1849 die
jetzige ev. luth. Imanuels Gemeinde sich bildete, unter Gottes Beistand.

Seine Kinder sind:

   . Carl Heinrich, geb. den 27 April u. get. den 30 April 1818.
     Taufpathe: Fridrich Schwier, confirmiert am Sonnt. n. Ostern 1832; gest.
     den 25 März 1839.

   . xref:DEC-BIO-Bleeke-02.adoc[Christian Fridrich], geb. den 7 Mai und get. den 13 Mai 1821.
     Taufpathe: Carl Fridrich Bleeke, confirmiert am Sonnt. Judica 1835.

. Carl Fridrich, geb. den 17 Juli u. get. den 20 Juli 1823.
Taufpathe: Christian Fridrich Bleeke; gestorben den 11 Mai 1825.
. xref:DEC-BIO-Bleeke-03.adoc[Carl Fridrich Wilhelm], geb. den 30 November u. getauft den 4
December 1825. Taufpathen: Fridrich Meier und Christ. Bleeke;
confirmiert um Ostern 1840 on Past. Möllmann in Cincinati.
. Christine Maria, geb. den 11 u. get. den 17 August 1828.
Pathen: Anna Soph. Schwier und Maria Meier; conf. von Past. Sihler, Ft.
Wayne ‚42
. Christine Sophie Eleonore, geb. den 13 August u. get. den 21
August 1831. Pathen: Christine Bleeke, conf. 1845 von Past. Sihler, Ft.
Wayne, Ind.
. Marie Louise Eleonore, geb. den 15 und get. den 24 November 1833.
Pathen: Louise Schwier und Marie Bleeke; conf. 1848 von Past.
Jäbker in Adams Co., Ind.
. Emilie, geb. den 11 März u. get. den [empty] 1837 in Cincinati
(Cincinnati) O. Getauft von Past. Lauer. Pathen: Christine Bleeke,
gestorben den 8 Sept. 1838, in ihrem Geburtsort Cincinati (Cincinnati).

== English Translation

page 32 (or 31)

No. 1

Johann Heinrich P. Bleeke

Son of Fridrich Bleeke and Anna Margaretha neé Volkening. He was born in
Leeteln (Leteln), canton of Windheim, county of Minden, Kingdom of
Prussia, on 3 November 1797. He was baptized in the same month by Pastor
Peikmann. His godfather was Johann Fridrich Volkening. He was confirmed
on Sunday after Easter, 1810.

He was married in spring of 1819 to Christine Maria Schwier, a daughter
of Christian Fridrich Schwier and Catharina Margareta neé Rösner. She
was born on 13 May 1798, and baptized in the same month in the
Protestant Lutheran Church in Frülle (Frille) by Pastor Peikmann. Her
godparents are: Anna Sophie Rösner and Christine Müller. She was
confirmed on Sunday after Easter, 1811.

The above mentioned Johann Heinrich Philipp Bleeke emigrated in 1834 to
the United States of North America. His family followed him there within
the following 2 years. After he lived for some time in Wheeling, VA, and
in Cincinati (Cincinnati), Ohio, he moved to this area in 1840. It was
through his efforts and with the help of God that the local Protestant
Lutheran Imanuel Church community formed in 1849.

His children are:

. Carl Heinrich, born on 27 April, and baptized on 30 April 1818.
Godfather: Fridrich Schwier; confirmed on Sunday after Easter,
1832; died on 25 March 1839.

. xref:DEC-BIO-Bleeke-02.adoc[Christian Fridrich], born on the 7^th^ of May, and baptized on
13 May 1821. Godfather: Carl Fridrich Bleeke, confirmed on Judica
Sunday, 1835.

. Carl Fridrich, born on 17 July, and baptized on 20 July 1823.
Godfather: Christian Fridrich Bleeke; died on 11 May 1825.

. xref:DEC-BIO-Bleeke-03.adoc[Carl Fridrich Wilhelm],
born on 30 November, and baptized on 4 December 1825. Godparents: Fridrich Meier
and Christ. Bleeke; confirmed on Easter 1840 by Pastor Möllmann in Cincinnati.

. Christine Maria, born on the 11^th^, and baptized on 17 August 1828.
Godparents: Anna Soph. Schwier and Maria Meier; confirmed 1842 by
Pastor Sihler in Ft. Wayne.

. Christine Sophie Eleonore, born on 13 August, and baptized on
21 August 1831. Godmother: Christine Bleeke; confirmed 1845 by Pastor
Sihler, Ft. Wayne, Ind.

. Marie Louise Eleonore, born on the 15^th^, and baptized on 24
November 1833. Godparents: Louise Schwier and Marie Bleeke; confirmed
1848 by Pastor Jäbker in Adams Co., Ind.

. Emilie, born on 11 March, and baptized on [empty] 1837 in
Cincinati (Cincinnati), Ohion. Baptized by Pastor Lauer. Godmother:
Christine Bleeke; died 8 Sept. 1838, in her birth town of Cincinati
(Cincinnati).
